src/zuuid.c
Solution: if we're asserting the length is accurate, we can just copy
the string as is. No need for memcpy and explicit termination (which
was off by one in any case).
=> Problem: zuuid_set_str was pointlessly broken

src/zsys.c
Use explicit SetCurrentDirectoryA() instead of character-set-dependent SetCurrentDirectory macro.
I have only tested this with VS2013, but calling SetCurrentDirectoryA() with a const char* parameter should be correct for any version.
=> Fix Unicode/MBCS ambiguity for VS2013

src/zsock.c
The bind and connect signs for attach were reversed, leading to confusion
=> Fix documentation for zsock_new_pub_

include/czmq_prelude.h
Solution: include at start (after system detection).
=> Problem: zmq.h is included rather late in czmq_prelude.h

include/czmq_prelude.h
Solution: define atoll to use _atoi64, on MSVC.
Fixes #883
=> Problem: MSVC does not provide atoll(), used by zsock

src/zframe.c, src/zmsg.c
Solution: if the lower-level send fails (EGAIN, EINTR, etc.) then
do not destroy the frame or message. This lets the calling app try
to send it again later.
=> Problem: zmsg, zframe destroying object even if send failed

src/zsock.c
Solution: cast to right size for format specifier.
Fixes #888
=> Problem: va_arg returning int, printf format expects byte

include/czmq_prelude.h
This one seems to completely fix https://github.com/zeromq/czmq/issues/870
=> Fix zsys_allocs export&import when build under msvc 2013

include/zhashx.h, src/zhashx.c
I am new to zmq and czqm. I was surprised to learn that there is zhashx_keys but no zhashx_values.
I needed the latter, so I implemented it. If possible I would like this included in czmq, hence the pull-request.
Code is pretty straightforward, mostly copy & pasted from zhashx_keys and modified to create a list of values instead of keys.
=> add zhashx_values

include/czmq_prelude.h
Solution: define these in "inevitable macros" section of czmq_prelude.h.
=> Problem: lack of min/max macros is causing some friction in Malamute

include/czmq_prelude.h
Solution: remove these macros. The Malamute code that uses them
can just take the long route.
=> Problem: min, max macros conflict with C++ limits header

src/zpoller.c, src/zsock.c
Solution: fix this in two places in test cases.
Fixes #899
=> Problem: zsock_fd returns SOCKET, not int, on Windows

doc/zdir.doc, doc/zdir.txt, doc/zhashx.doc, doc/zhashx.txt, doc/zpoller.doc, doc/zpoller.txt, doc/zsock.doc, doc/zsock.txt, doc/zsys.doc, doc/zsys.txt, include/czmq_prelude.h, include/zsys.h, src/zbeacon.c, src/zsys.c
Since mode_t is unsigned on at least OS/X and probably other platforms too.
Also some cosmetic changes and man page rebuilds.
=> Fixed zsys_file_mode to return int

include/zloop.h, src/zloop.c
This broke Hydra.
Solution: do not delete ticket in handler, but flag it and move to
end of ticket list, then delete after ticket handlers are all done.
=> Problem: zloop crashes if ticket handler deletes own ticket

include/czmq_prelude.h
solution: add __IS_64BIT__ guard
=> problem: zmalloc counter breaks build on 32 bit systems

src/zbeacon.c
Solution: print interface name in debug trace
=> Problem: no tracing of interface, in zbeacon setup

include/czmq_prelude.h, src/zclock.c
`clock_gettime` is `clock_get_time` on iOS and OS X. The conditional
compilation was only handling OS X.
=> Problem: compile error when compiling for iOS

configure.ac
It should only happen in case the argument
./configure --with-makecert
is given.
=> Problem: czmq is always building makecert

configure.ac
Reverts zeromq/czmq#913
Reverted because the addon is useful being build by default.
=> Revert "Problem: czmq is always building makecert"

configure.ac
When building this library building also the makecert add-on program is the default, and an option to turn this off isn't there yet. The option to _do_ build is present (--with-makecert) but isn't necessary, as it's the default behaviour.
Change inverts this options' semantics and renames it to --without-makecert, which resolves the problem.
(This is the next iteration at zeromq/czmq#913.)
=> Problem: there isn't an option to build library without makecert add-on program

configure.ac
In response to PR #916 which results in an inconsistency in behavior and documentation as seen by `./configure --help`
The output of which now includes:
```
Optional Packages:
--with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
--without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
--with-pic[=PKGS]       try to use only PIC/non-PIC objects [default=use
both]
--with-gnu-ld           assume the C compiler uses GNU ld [default=no]
--with-sysroot=DIR Search for dependent libraries within DIR
(or the compiler's sysroot if not specified).
--with-makecert         Include the program makecert for compilation and
installation [default=yes].
--with-gcov=yes/no      With GCC Code Coverage reporting.
--with-pkgconfigdir=PATH
Path to the pkgconfig directory [[LIBDIR/pkgconfig]]
```
The …
=> Correct makecert with argument for consistency.

doc/zloop.doc, doc/zloop.txt, doc/zsys.doc, doc/zsys.txt, src/zsys.c
This reverts commit f47a1df8729141bfa78f4fe920b739d0ea4e3ec6, reversing
changes made to f2235576a1c1c6e5350769942be44cfc21ac8490.
See comments: https://github.com/zeromq/czmq/pull/920
=> Revert "Merge pull request #918 from hintjens/master"

CMakeLists.txt, model/build-autoconf.gsl, model/build-cmake.gsl
This retrofits all manual edits back to the templates under the assumption that the outputs are authoritative, since the outputs are what have been built to date.
It's possible that there were template changes that were not applied to outputs and are now removed. It's hard to tell, and safer to have the templates generate the current outputs.
=> Problem: Templates outputs have been manually edited.

include/zloop.h, include/zpoller.h, src/zloop.c, src/zpoller.c, src/zsock.c, src/zstr.c
After receiving an interrupt, all zloops and zpollers are put into a
state where they refuse to start/continue running. Unfortunately, this
makes it impossible to terminate a system of zactors in a controlled
order.
As an example, assume there is one actor used to linearize and format
output of all other actors. We definitely want to shut down this actor
after all others, so that we are able to log all events which occur
during systen shutdown. This doesn't work at the moment when the using
the default signal handling approach.
The patch adds two methods which can be used to make zloops and
zpollers ignore the zsys_interrupted global.
void zloop_ignore_interrupts(zloop_t *self);
void zpoller_ignore_interrupts(zpoller_t *self);
Note that there were two additional places in the code base …
=> can't shut down an actor system in a controlled way after interupt

configure.ac, src/zdigest.c
Hello, I have stumbled upon failing zdigest test on bigendian machines in fedora.
http://s390.koji.fedoraproject.org/koji/buildinfo?buildID=303454
http://ppc.koji.fedoraproject.org/koji/buildinfo?buildID=296552
Code in sha1.c seems bigendian compatible, but endianess is not checked in configure. So I have added check in configure.ac. To use result of endianity check, platform.h is included in zdigest.c.
I have tested it on s390x, powerpc64(le), x86, aarch64, arm( build/tests pass) , but it still fails on s390(31bit)..., still looking in to it.
=> Fix sha1 on bigendian machines.

ci_build.sh, src/Makemodule-local.am, src/zgossip_msg.c
Solution: Make check-verbose.
Rationalle: Newer versions of automake >= 1.13 force `make check` to be
run through a parallel test runner which turns off all output. So we
need a way to at least see the non-verbose output in that sort of
environment, hence check-local.
check-verbose comes about because when CI failures or hangs occur, there
is very little information to go on, so making it always dump as much
information as possible should hopefully help diagnose these issues in
future.
=> Problem: No way to run verbose tests via make

src/Makemodule-local.am, src/Makemodule.am
Solution: Regenerate from zproject - project selftest not added to the
TESTS which are run by the parallel test runner (where stdout is
ignored)
Fixes #969
=> Problem: make check runs the tests twice

src/zhash.c
Memory leak when zhash_insert with autofree fails by already existing key. 
Test codes can check zhash_insert fail case and memory leak.
=> Fixed memory leak in zhash_insert with autofree

api/zlist.xml, bindings/python/czmq.py, bindings/qml/src/QmlZlist.cpp, bindings/qml/src/QmlZlist.h, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/zlist.rb, include/zlist.h, src/zlist.c
Solution: Introduce an equals function to the list which can be used by _exists and _remove methods.
I didn't choose the compare method for this problem as it doesn't work for equality. Of course I could have fix the compare method to work like strcmp for example but this would have broken user space.
=> Problem: There is no easy way to check if two list items are equal

include/czmq_prelude.h
Solution: don't define uint if __USE_MISC is defined
Fixes #984
=> Problem: uint redefined on Linux in some cases

src/zlist.c
Problem:zlist_sort function wont work in some case (zlist: "b", "a", "c" ) due to incorrect implement of the comb sort algorithm.
Solution:fix up the comb sort algorithm in zlist_sort function.
=> Problem:zlist_sort function incorrect

src/zsys.c
Changed zmalloc to malloc for string allocation.
=> zsys_vprintf was needlessly using zmalloc

bindings/python/test.py
From https://docs.python.org/2/library/ctypes.html:
The string_at method expects a NULL terminated string if it isn't supplied with the size of address space.
This fix uses the size of the message for the string_at method. It fixes the failing unittest.
Tested on 32bit debian jessie.
=> fix for failing test.py #998

include/zuuid.h, src/zuuid.c
This eats up valuable random data, and potentially blocks.
Solution: add zuuid_new_from (), and use this in zuuid_dup ().
=> Problem: creating UUID from existing data is inefficient

src/zsock.c
SOLUTION: use correct picture format in zsock_recv (u->U)
Fixes #1004.
I suggest to drop the deprecated format "u". It's too
easy to mix the two (as evidenced by the crash).
=> PROBLEM: zsock_test segfaults on OS X

Makefile.am, api/zmsg.xml, bindings/python/czmq.py, bindings/qml/src/QmlZmsg.cpp, bindings/qml/src/QmlZmsg.h, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/zmsg.rb, include/zmsg.h
Causes loss of prototype when regenerating project.xml.
Solution: add it to right place.
Incidental fix, the Makefile also reflects zproject PR #192.
=> Problem: zmsg_sendm not defined in API model

doc/Makefile.am
Solution: fixed in zproject, regenerate here.
=> Problem: does not install man pages if BUILD_DOC is off

include/zmsg.h, src/ziflist.c, src/zmsg.c
Solution: remove this.
Also remove two bogus CZMQ_EXPORTs in sources.
=> Problem: ziflist_print uses illegal for declaration

src/zctx.c, src/zsys.c
Setting zsys_handler_set(NULL) stops ZMQ taking over SIGINT and SIGTERM
when using new zsock API (zsys backend), but not when zctx are used.
Add new handle_signals static bool (default true) to determine whether
a user wants ZMQ to handle signals or not.
Pull request #1008 fixed the issue with zsock by making zsys_init check the flag, but when using zctx it is still broken. I did a very small refactor to check the environment variables and the flags directly in zsys_catch_interrupts() instead of in zctx_new() and zsys_init(). I added a new static bool rather than re-using s_first_time because I felt that it makes the code and the intended behaviour clearer.
I tested this on Debian 7 and 8, with 2 different softwares that use CZMQ with zctx. All make check tests pass.
Thanks!
EDIT: Even …
=> Fix zsys_handler_set(NULL) with zctx

src/zloop.c
It deals properly with tickets that are deleted in a handler, though
not with tickets that are deleted in other handlers.
Solution: don't call handler on deleted tickets.
=> Problem: zloop will call handler on deleted tickets

acinclude.m4, src/CMakeLists-local.txt
As reported in https://github.com/zeromq/zproject/issues/199 CZMQ uses Pthread symbols without linking to it. Although this does not cause build problems since ZMQ links to Pthread, it causes errors to be printed by the Debian build environment, since a library is expected to link against all its dependencies.
Finally, with autotool -std=gnu99 is used to build, but not with CMake, which causes a compile error since zdir uses C99's ‘for’ loop initial declarations. So, gnu99 is added to CFLAGS in the project-local CMake hooks.
Please note that this won't have any effect until https://github.com/zeromq/zproject/pull/202 is merged and ./generate.sh is run again on this project.
=> Link to pthread

acinclude.m4
Android's libc, Bionic, does not provide a -pthread flag to link,
but instead links automagically when it founds <pthread.h> included.
Use AC_MSG_WARN instead of AC_MSG_ERR to avoid failing the build.
After this commit, if -pthread is not possible like on Android, the build will continue and this will be printed to warn the user:
"configure: WARNING: cannot link with -pthread."
=> Warning instead of error if cannot link pthread

.travis.yml, builds/cmake/ci_build.sh
Hello,
Is there any particular reason for not having a CMake target in Travis?
If not, this PR enables it. As you can see from here: https://travis-ci.org/bluca/czmq/builds/72932752 it seems to work fine :-)
=> Add Travis target for CMake

src/CMakeLists-local.txt
Turns out the CMake special flags are not enough for pthread, find_package needs to be run as well.
If the Threads package is not found, a warning will be printed but the build will continue. :-)
You can check a Travis run which includes a CMake target here: https://travis-ci.org/bluca/czmq/builds/72931553
=> CMake needs find_package(Threads) to link pthread

src/zframe.c, src/zmsg.c, src/zproxy.c, src/zsock.c
Ported my analysis code from czmq 2.2.0 to 3.0.2 and noticed a 50% slowdown with czmq 3.0.2.  Profiled the code on OSX and saw a huge overhead in getsockopt being called from sock_resolve from my calls to zmsg_send.  zsock_resolve was converting zsock_t* to a void* and then sub-functions were then calling zsock_resolve on the void*. This commit passes the original zsock_t to any function that then calls zsock_resolve so that getsockopt is almost never called.  This fixed my slowdown.
=> Pass zsock_t instead of handle to zsock_resolve aware functions 

CMakeLists.txt, bindings/python/czmq.py, configure.ac
Solution: Regenerate using latest zproject to correctly decorate methods which match a keyword
=> Problem: Python tests failing.

CMakeLists.txt, bindings/ruby/lib/czmq/ffi/zactor.rb, bindings/ruby/lib/czmq/ffi/zdir.rb, bindings/ruby/lib/czmq/ffi/zdir_patch.rb, bindings/ruby/lib/czmq/ffi/zfile.rb, bindings/ruby/lib/czmq/ffi/zframe.rb, bindings/ruby/lib/czmq/ffi/zhash.rb, bindings/ruby/lib/czmq/ffi/zhashx.rb, bindings/ruby/lib/czmq/ffi/ziflist.rb, bindings/ruby/lib/czmq/ffi/zlist.rb, bindings/ruby/lib/czmq/ffi/zloop.rb, bindings/ruby/lib/czmq/ffi/zmsg.rb, bindings/ruby/lib/czmq/ffi/zsock.rb, configure.ac
Solution: regenerate from the latest Zproject version to add back autoconf and CMake project-local hooks that were removed in #1051 and fix the CMake CI build.
=> Problem: local hooks generated from Zproject were removed

.travis.yml, builds/check-py/ci_build.sh, builds/cmake/ci_build.sh, builds/qt-android/android_build_helper.sh, builds/qt-android/ci_build.sh, ci_build.sh
This PR makes the CI build scripts compatible with OSX on Travis. Fixes #1053. Note that until OSX build is enabled on a project by emailing support@travis-ci.com, the option in travis.yml will have no effect.
=> Travis osx

.travis.yml, builds/check-py/ci_build.sh, builds/cmake/ci_build.sh, ci_build.sh
Hello,
As discussed in https://github.com/zeromq/libzmq/pull/1529 here's a PR to switch from VM to container based Travis CI builds. Needed changes were removing "sudo" and installing in local directory rather than in the default /usr/local.
Also -x is set in ci_build.sh, since it prints the executed commands to the log, which is very helpful when debugging.
CMake is particularly quirky, it took a while to make it work, it really didn't want to accept the local pkg-config path!
Please note that the build failures are due to ZMQ test failing, please see this build with ZMQ pinned to the latest working commit for an all-green CI build:
https://travis-ci.org/bluca/czmq/builds/75871849
=> Enable container-based build

src/zactor.c
In zactor_new(), if zsys_create_pipe() returns an error, the function returns NULL and the reference to shim is lost and the allocated buffer leaked. Very unlikely to matter in practice since it's in the error path, but still worth fixing.
=> Fix memory leak in zactor_new error path

configure.ac, src/Makemodule.am
This forced zuuid_new to always use /dev/urandom, which failed in
heavily multithreaded cases (ran out of open file handlers).
Solution: use libuuid, via zproject.
=> Problem: not using libuuid

README.md, doc/ztrie.doc, doc/ztrie.txt, src/ztrie.c
Solution: Fix typos and rework grammar.
=> Problem: ztrie selftest comments have typos and weird grammar.

CMakeLists.txt, builds/qt-android/build.sh
Solution: Don't use the optional dependencies at all until this issue has been fixed in zproject.
=> Problem: Tests for cmake and qt android failed as they added a optional dependency as required

src/zframe.c
libzmq PR https://github.com/zeromq/libzmq/pull/1577 changed a public API function call from
zmq_msg_get_routing_id to zmq_msg_routing_id, so update call in
zframe.c.
=> Fix zframe.c build breakage

README.md, doc/ztrie.doc, doc/ztrie.txt, include/ztrie.h, src/ztrie.c
Solution: Use the asterisk operator to indicate a match on the rest of the route/path
There are some limitation to the use of the asterisk operator:
1. must be a leaf, otherwise it is considered a string
2. cannot have siblings
3. cannot have children
=> Problem: ztrie cannot match routes/paths of variable length

Makefile.am, src/zproxy.c
systems in particular the CI-Server. Which results in test build failures if this flag is not set on the development system.
Solution: Activate the flag by default to find these compiler errors early.
Also: fixed the failing zproxy build!
=> Problem: The CFLAG '-Werror=format-security' is used by default in some

src/ztrie.c
The file "ztrie.c" does not compile on Windows due to lack of a "strndup" function. Added one to source file - there's likely a better location for the function, but this gets things working.
=> Updated ztrie.c with a strndup function so it will compile on Windows

src/zproxy.c
Saga details: https://github.com/zeromq/czmq/pull/1087
=> Turned off backend socket authentication testing for zproxy to help with CI build timeouts

src/zproxy.c
Reduced the scope of the zproxy authentication testing. Updated test code to only focus on exercising new commands instead of trying to comprehensively test every possible combination of security. Code still follows zauth testing pattern, but intermingles frontend and frontend+backend tests for each major type of authentication functionality. Test code also now produces a better functionality example.
=> Simplified zproxy authentication tests

builds/msvc/platform.h, include/czmq_prelude.h, src/zuuid.c
name and due to changes in zproject won't get a 'LIB' prepended.
Solution: Remove the prepended 'LIB' when checking for the library uuid.
=> Problem: The defines for optional dependencies are based on the library

api/zsock.xml
Solution: Change the api file accordingly to the changes made by
zproject.
Methods with variadic arguments no longer have an argument which has
solely the attribute variadic but the variadic start element defines the
variadic attribute.
=> Problem: ./generate.sh will cause zsock.h to get corrupted.

FindUuid.cmake, FindZeroMQ.cmake, appveyor.yml
In #1094, a CI test for Windows was requested.
Appveyor provides a framework for Visual Studio on Windows.
See http://www.appveyor.com/
Notes:
- Only tests Visual Studio 2015
- It builds 32- and 64-bit
- It builds Release and Debug
- It will build the libzmq dependency everytime
- It does not build and run the libzmq tests
- It will run the selftest of czmq after the build
- It will produce a zip with the built files, which can be downloaded
from the artifacts page.
- Remote debugging (using rdesktop) is possible. See
http://www.appveyor.com/docs/how-to/rdp-to-build-worker
on how to pause the build and rdp to the worker.
Known problems:
- In FindUuid.cmake, a bad path is set. So UUID is not used in Visual Studio.
- No output of the czmq_selftest
- The self test fails at an assertion. For …
=> Add Windows Visual Studio CI appveyoyer.yml file

src/zdir.c
Bug https://github.com/zeromq/czmq/issues/527
czmq_selftest calls zdir_test, which enumerates the current and parent working directories. This breaks `make check` when the parent directory contains files with chmod 600 owned by other users (problematic if the build directory is somewhere shared, like /tmp/)
Since czmq_selftest is called in the czmq base directory by `make check`, it makes sense for this test to refer to "src" and "." instead of "." and "..", preventing zmq from playing outside its build directory
=> fix zdir traversing too high

appveyor.yml, src/timeout.py
This fixes my last Windows CI PR.
False detection of a non-finishing test will not cause a failed test.
Anyhow, czmq_selftest has some issues.
- On Windows, not all output is redirected into the web log (no subtest is shown at all)
- Assertion errors on windows are not shown in the web log
- On Linux, redirection of the output of czmq_test will also nog show all output. (#1129)
On my system, the second one will not show all output. Maybe the issues are related.
=> Use timeout on Windows CI for czmq_selftest

src/zdir.c
Have moved creation of zdir-test-dir to before the zdir-diff test begins
=> Problem: zdir_test needed a test directory

src/zcert.c, src/zdir.c, src/zdir_patch.c, src/zhashx.c, src/zlist.c, src/zlistx.c, src/zloop.c, src/zmsg.c, src/zmutex.c, src/zproxy_v2.c, src/zsocket.c, src/zstr.c, src/ztrie.c
CLASS specifies "condition? first: second" yet various sources
use "condition ? first : second".
Solution: fix the code.
Argument: in CLASS, punctuation sticks to the rules for written
English where possible. So:
phrase;     not phrase ;
(phrase)    not ( phrase )
[phrase]    not [ phrase ]
1 + 2       not 1+2
a? b: c     not a ? b : c
=> Problem: various sources have whitespace issues

src/zarmour.c, src/zproxy.c, src/ztrie.c
Specifically:
* they use inline declarations in for loops, which is not standard C
* they use the variable name 'i' in loops, which is banned
I've no idea how the inline declarations are passing. Perhaps someone
has tweaked zproject to allow this on gcc. On MSVC since we use C++
it will not be caught.
Solution: fix the sources.
=> Problem: several sources break style with CLASS

bindings/python/czmq.py, bindings/python/test.py
The actual problem is that Python 3 does not provide a low level
buffered I/O (FILE*) API, specifically "pythonapi.PyFile_FromFile" and
"pythonapi.PyFile_AsFile". Merely importing "czmq" on Python 3 gives
"AttributeError: … symbol not found".
Solution: use the Standard C library functions on Python 3. Also, adjust
the test battery to run on Python 3.
=> Problem: bindings do not run on Python 3

src/zframe.c
Solution: add ifdef ZMQ_SERVER around calls to zmq_msg_set_routing_id,
which is only available in libzmq 4.2 and later
=> Problem: zframe fails to compile, missing ifdef

src/zsock.c
Should the mapping of zmq_ctx_new to zmq_init in czmq_prelude.h pass some default value of io_threads maybe? Otherwise it just won't compile without changing the user's code.
=> Fix libzmq2 build and add zsock_t resolve test

.gitignore, README.md, api/zframe.xml, bindings/jni/src/main/c/org_zeromq_Zframe.c, bindings/jni/src/main/java/org/zeromq/Zframe.java, bindings/python/czmq.py, bindings/qml/src/QmlZframe.cpp, bindings/qml/src/QmlZframe.h, bindings/qt/src/qzframe.cpp, bindings/qt/src/qzframe.h, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/zframe.rb, doc/zframe.txt, include/zframe.h
@hintjens - PR #1139 removed the implementation of zframe_send_reply, but it was left in the api XML and so in the generated bindings and headers. This causes check-py to fail.
This PR removes the definition from the XML of zframe and regenerates the bindings accordingly. Is this the right thing to do, or is the implementation just out temporarily? Please decline if that's the case :-)
I've also updated the documentation. Are the .doc files somehow autogenerated or should they be updated manually?
=> Fix check-py failure

bindings/python/czmq.py
Solution: Regenerate from zproject which fixes this at source.
Fixes #1149
=> Problem: Python bindings for Zpoller constructor had incorrect assert.

src/zcert.c, src/zclass_c.gsl, src/zconfig.c, src/zhash.c, src/zmsg.c, src/zsock.c, src/zstr.c, src/zsys.c
According to the documentation of zsys_vprintf(), one should use
zstr_free() instead of free() to free those strings.
This closes issue #1155.
Tested by compiling using `./configure`, `make`, and `make check-local`.
=> use zstr_free() instead of free()

api/zactor.xml, api/zdir.xml, api/zdir_patch.xml, api/zfile.xml, api/zframe.xml, api/zhash.xml, api/zhashx.xml, api/ziflist.xml, api/zlist.xml, api/zloop.xml, api/zmsg.xml, api/zpoller.xml, api/zsock.xml, api/zsock_options.gsl, api/zsock_options.xml, api/zstr.xml, api/ztrie.xml, api/zuuid.xml, src/sockopts.gsl
This also fixes paths to the license file and actually turns on the `<include>` tag within class API XML files.
This is related to #1164.
=> Include zsock_option functions into zsock.xml

bindings/ruby/lib/czmq/ffi/zactor.rb, bindings/ruby/lib/czmq/ffi/zhash.rb, bindings/ruby/lib/czmq/ffi/zhashx.rb, bindings/ruby/lib/czmq/ffi/zlist.rb, bindings/ruby/lib/czmq/ffi/zloop.rb, bindings/ruby/lib/czmq/ffi/ztrie.rb
Solution: Regenerate Ruby bindings to include callback result coercion
to pass it back to C.
=> Problem: missing callback result coercion

include/zsock.h
Solution: We can safely remove it as the libzmq version is carefully handled in the source file.
=> Problem: Define for server and client socket is unnecessary

src/zpoller.c
Making sure zmq_poller is available before checking server and client sockets
=> problem: zpoller test can fail if libzmq is not up to date

include/zarmour.h
ZARMOUR_MODE_BASE16_HEX because of everywhere was used ZARMOUR_MODE_BASE16
=> renamed ZARMOUR_MODE_BASE16_HEX to ZARMOUR_MODE_BASE16

api/zarmour.xml
=> Problem: typo in zarmour enum constant

src/ztrie.c
Solution: make method take const char * and explicitly cast to char *
=> Problem: ztrie does not compile as it discards const qualifier

src/Makemodule.am
Solution: use latest zproject to install this file as well
=> Problem: zsock_option.xml is not installed

api/zsock.xml
Solution: Further zproject assues that includes are withing API directory. Thus make path from api/zsock.xml to api/zsock_options.xml realtive to api/zsock.xml.
=> Problem: Latest zproject assumes that API includes are relative to API file

src/zconfig.c
Even if the handler returns -1, it still recursively processes every
first child of the current zconfig item.
Solution: Fail early as soon as a handler returned -1.
I'm **NOT experienced** in C. Maybe this is completely wrong. But IMHO this is correct (and it makes my CZTop Ruby binding test suite pass).
=> Problem: zconfig_execute() doesn't fail early

src/zconfig.c
Solution: make s_config_execute() return -1 instead of 0
This is a follow-up of zeromq/czmq#1203.
=> Problem: unintuitive failure return value

api/zconfig.xml, bindings/jni/src/main/c/org_zeromq_czmq_Zconfig.c, bindings/python/czmq.py, bindings/qml/src/QmlZconfig.cpp, bindings/qml/src/QmlZconfig.h, bindings/qt/src/qzconfig.cpp, bindings/qt/src/qzconfig.h, bindings/ruby/lib/czmq/ffi/zconfig.rb, include/zconfig.h
When writing the API file, I only looked at the documentation and assumed that all `char *` are fresh when in fact some of them are simply mutable.
I also missed that zconfig_load(), zconfig_loadf(), and zconfig_savef(), of course, return fresh objects.
This also removes the attribute `constant = "1"` from some of the arguments, which is useless now.
=> zconfig fresh/mutable fixes

bindings/jni/build.gradle, bindings/jni/src/main/java/org/zeromq/czmq/Zarmour.java, bindings/jni/src/main/java/org/zeromq/czmq/Zconfig.java, bindings/jni/src/main/java/org/zeromq/czmq/Zdir.java, bindings/jni/src/main/java/org/zeromq/czmq/ZdirPatch.java, bindings/jni/src/main/java/org/zeromq/czmq/Zfile.java, bindings/jni/src/main/java/org/zeromq/czmq/Zframe.java, bindings/jni/src/main/java/org/zeromq/czmq/Zhash.java, bindings/jni/src/main/java/org/zeromq/czmq/Zhashx.java, bindings/jni/src/main/java/org/zeromq/czmq/Ziflist.java, bindings/jni/src/main/java/org/zeromq/czmq/Zlist.java, bindings/jni/src/main/java/org/zeromq/czmq/Zloop.java, bindings/jni/src/main/java/org/zeromq/czmq/Zmsg.java, bindings/jni/src/main/java/org/zeromq/czmq/Zpoller.java, bindings/jni/src/main/java/org/zeromq/czmq/Zsock.java, bindings/jni/src/main/java/org/zeromq/czmq/Zstr.java, bindings/jni/src/main/java/org/zeromq/czmq/Ztrie.java, bindings/jni/src/main/java/org/zeromq/czmq/Zuuid.java
Solution: make this a public property. This opens the door to
general mayhem but it lets us pass CZMQ classes to other methods
in e.g. Zyre.
=> Problem: .self is private so we can't use it from other packages

bindings/qt/src/qzconfig.cpp
Solution: Re-generate with latest zproject to fix it.
=> Problem: Qt bindings don't work as qzconfig has an extra comma with method reload.

api/zconfig.xml, api/zframe.xml, api/zhash.xml, api/zhashx.xml, api/zmsg.xml, api/zsock.xml, api/zuuid.xml, include/zconfig.h, include/zframe.h, include/zhash.h, include/zhashx.h, include/zmsg.h, include/zsock.h, include/zuuid.h, src/zmsg.c
Solution: expose all singletons that return fresh instances as
constructors.
Note: this changed the signature for zmsg_load(), which was a
mix of constructor and method.
Fixes #949
Among other things.
Breaks the JNI and Python binding generators, probably.
=> Problem: many constructors are disguised in API model

api/zsock.xml, include/zsock.h, src/zsock.c
Returned objects are owned by caller, who must destroy them.
Solution: fix this.
Fixes #1223
=> Problem: doc for zsock_brecv is inaccurate

src/czmq_selftest.c
A printf statement occurred before the block-local variable. MSVC
failed to compile. Swapping the order fixes the problem.
=> Problem: czmq_selftest block-local variable fails for MSVC

src/zcert.c, src/zmakecert.c
Solution: provide string literals as format
This closes #1230.
=> Problem: unsafe use of format

include/czmq_prelude.h, src/zbeacon_v2.c
Fixes #1238 
Renamed also `in4addr` to `ipv4addr` for consistency.
=> Solution: rename conflicting defines to `ipv4addr` and `ipv6addr`

src/zcert.c
This leads to being able to give the empty string as filename and it'll
create a single file "_secret".
Solution: check zcert_save_public()'s return value
This is for #1244.
=> Problem: zcert_save() ignores result of zcert_save_public()

api/zcert.xml, include/zcert.h, src/zcert.c
Solution: add zcert_unset_meta()
This also adds a missing assert in zcert_set_meta().
=> Problem: no way to unset zcert metadata

src/zcert.c
Solution: assert name and format as well
As discussed on #1246.
=> Problem: zcert_set_meta() doesn't assert enough

api/zproc.xml, bindings/jni/src/main/c/org_zeromq_czmq_Zcert.c, bindings/jni/src/main/c/org_zeromq_czmq_Zproc.c, bindings/jni/src/main/java/org/zeromq/czmq/Zcert.java, bindings/jni/src/main/java/org/zeromq/czmq/Zproc.java, bindings/python/czmq.py, bindings/qml/src/QmlZcert.cpp, bindings/qml/src/QmlZcert.h, bindings/qml/src/QmlZproc.cpp, bindings/qml/src/QmlZproc.h, bindings/qt/src/qzcert.cpp, bindings/qt/src/qzcert.h, bindings/qt/src/qzproc.cpp, bindings/qt/src/qzproc.h, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/zproc.rb, include/zproc.h, src/zproc.c
This prohibits any method with that name.
Solution: use "biface" for "broadcast interface" in the zproc class.
=> Problem: "interface" is a reserved word

src/zpoller.c
Solution: fix here. CZMQ build will be broken until both patches
are merged.
=> Problem: libzmq master changed zmq_poller_close -> destroy

bindings/jni/android/build.sh
android jni build.sh: ensure "gradle build jar" is run before, otherwise compilation will fail with missing headers.
=> android jni build.sh: ensure "gradle build jar" is run

api/zproc.xml, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/zproc.rb, include/zproc.h, src/zproc.c
Solution: add zproc_has_curve()
This closes #1268.
=> Problem: bindings need to know if CURVE security is available

.gitignore
Or, in case of the .vimsession file, I just don't want git to consider
it dirt.
Solution: gitignore them
Since those other files in the build directory aren't tracked, I assume it's okay to gitignore them.
=> Problem: repetitive need to delete non-tracked files after generating

src/zloop.c
This fixes issue #1278 by making the ticket handler return code detection exactly similar to what is done for a timer handler when -1 is returned.  This ensures that a -1 returned by a ticket handler does cause zloop_start to terminate as described in its API.
Verified on an Ubuntu 14.04LTS (x64) system.  Without the fix, a ticket handler returning -1 does not cause zloop_start to terminate.  With the fix in place, a ticket handler returning -1 does indeed cause zloop_start to terminate and its return code is -1.  This behavior now matches the API documentation.
=> Fixing zloop_start so that it terminates when ticket handler returns -1

src/zstr.c
Solution: don't run SERVER/CLIENT tests unless ZeroMQ supports
those socket types.
Fixes #1283
=> Problem: src/zstr.c:336: zstr_test: Assertion `server' failed.

builds/android/build.sh, configure.ac
Solution: use parallel make (-j 4) and don't build man pages.
Via zproject.
=> Problem: Android build is too slow

src/zbeacon.c
Solution: only close UDP socket if fd isn't 0
This closes #1281.
=> Problem: unconfigured zbeacon closes STDIN on destruction

src/zauth.c
Analysis: test code was wrongly assuming it was always safe to send
on a socket after 'connect'. In fact if the connect fails due to an
authentication failure, there is a small window between calling the
'connect' and the peer rejecting the connection. In this window, a
send will work. After the window, it will hang forever.
Solution: set send timeout on test socket.
=> Problem: zauth sometimes hangs in self test

.travis.yml
Solution: add Valgrind to the Travis dependencies
make memcheck was added a while ago, but build-deps were missing from travis.yml.
Please note that make memcheck still fails due to many reported leaks by valgrind.
=> Problem: Travis CI fails due to missing Valgrind

configure.ac, src/libczmq.pc.in
Solution: Make libsodium an optional dependency
Note: This change has been done in zproject which generates czmq's
configuration files.
Fixes #1294
=> Problem: Cannot compile czmq without libsodium

api/zchunk.xml, api/zclock.xml
Solution: use new 'msecs' type instead
(Also fixed bogus license header).
=> Problem: 'clock' type no longer supported in zproject

api/zsock_option.xml, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/zsock.rb, include/zsock.h, include/zsockopt.h, src/sockopts.xml, src/zsock_option.gsl, src/zsock_option.inc, src/zsockopt.c, src/zsockopt.gsl
This PR:
* fixes a wrong filename in a generated header comment
* adds the ability to use the `test_value` attribute for integers as well
* adds the three options (r/w) `heartbeat_ivl`, `heartbeat_ttl`, and `heartbeat_timeout`
* regenerates the affected API XML, C sources, and Ruby binding
`make check` is happy.
=> add ZMTP 3.1 heartbeat options

api/zcert.xml, api/zframe.xml, api/zlistx.xml, api/zloop.xml, api/zmsg.xml, api/zpoller.xml, api/zsock.xml, api/zsock_option.xml, api/zstr.xml, bindings/ruby/lib/czmq/ffi.rb, include/zcert.h, include/zframe.h, include/zlistx.h, include/zloop.h, include/zmsg.h, include/zpoller.h, include/zsock.h, include/zstr.h, src/sockopts.xml, src/zsock_option.gsl
* socket options can be draft now (like heartbeat options)
* mark a few unreleased, recent API functions as draft
* regenerate Ruby binding
This allows CZTop to be used with the current stable release of CZMQ.
=> draft related improvements

configure.ac, include/czmq_library.h, src/zsys.c
We used to run zsys_test first, so it could test set_io_threads ()
which has to be the first thing a process does before creating any
sockets.
With zproject's test framework, we don't control the order of test
cases (and this is good, they should not be dependent). Now zsys is
called late, and so the call to set_io_threads () asserts.
Solution: remove this specific test.
=> Problem: czmq_selftest failing on zsys

configure.ac
Solution: fixed in zproject, regenerated here.
Fixes #1320
=> Problem: selftest build must be optional

bindings/qt/common.pri
Solution: make qmake read pkgconfig
Note: This change has been done in zproject
=> Problem: qt bindings won't compile against draft APIs

include/czmq_library.h
=> Problem: CZMQ doesn't build with MSVC without DRAFT_API definition

src/zsys.c
Caused by selftest that runs zsys_test after other tests,
when code was desiged to be run as first test case.
Solution: do not test zsys_set_max_sockets () which cannot be
used after any sockets are created.
=> Problem: zsys_test is failing

setup.py
Solution: generate setup.py using zproject.
Now "python setup.py install" works.
=> Problem: czmq python bindings are a bit painful to install

include/czmq_prelude.h
This header file is empty in 4.2.0 and was removed on 2016/02/01.
Solution: include in ZMQ versions prior to 4.2.0.
=> Problem: czmq_prelude.h refers to zmq_utils.h

bindings/jni/android/CMakeLists.txt, builds/android/build.sh, builds/android/ci_build.sh, ci_build.sh, configure.ac
Draft API is exposed via JNI binding but draft classes were not
built properly.
Solution: fixed in zproject, regenerated here.
=> Problem: JNI/Android build was not working

.travis.yml, builds/cmake/ci_build.sh, builds/stable_zmq/ci_build.sh, ci_build.sh, src/zsock.c
When the main CI script became autogenerated by zproject a while ago, the CI builds with stable versions of libzmq were broken, and all builds were done with the dev repository. As a result we didn't notice when the build with a version of libzmq without ZMQ_SERVER (anything but the dev repo) broke due to missing ifdef.
I've added a new build type, zmq_stable, to avoid this problem in the future.
Few other small fixes, including not using libsodium in the CMake build and using the correct parameter to avoid building with docs in the CI.
I'm still looking at the Valgrind issue. The problem is timing: some tests fail when running in a slower environment, which is not nice at all. I'm trying to bandaid them by adding sleeps to let the sockets enough time to stabilize, which is arguably …
=> Problem: build with stable ZMQ broken

CMakeLists.txt, Makefile.am, configure.ac
CZMQ doesn't even need this, it can generate its own UUIDs.
We may need a way to add optional packages that aren't
dependencies and aren't detected (like libsodium in libzmq).
Solution: remove libuuid dependency
=> Problem: libuuid dependency is fragile and unnecessary

api/zlist.api, include/zlist.h, src/zlist.c
The docs say this does an ASCII sort but in fact it does not,
and it won't work unless you pass a comparison function. This
is over-design for 90% of cases.
Solution: extend API slightly so that a NULL comparison function
gets treated as "strcmp", giving the desired effect for most
simple cases.
=> Problem: zlist_sort does not work according to docs

src/zauth_v2.c
This is a backport to the zauth hanging problem
described in commit zeromq/czmq@b6805df78 by hintjens.
=> Problem: zauth_v2 sometimes hangs in self test

src/zsys.c
Solution: fix the call to use explicit printing via PRIi64 and casting to int64_t
=> Problem: printf "%d" format is pedantically wrong for pid_t getpid() return type

src/zframe.c
I've added a version gate around zframe_meta and slightly modified the unit test to ensure that it won't segfault.
@bluca I haven't committed the GSL update yet. When I ran `gsl project.xml` it seemed to make a lot of trivial changes to a lot of files (34 in total). I assume that this isn't expected?
=> Fix issues with previous zframe_meta PRs

bindings/nodejs/index.js
Solution: Export the constants with the native bindings
Running into issues using the bindings as is, though this is a start for how the index can look. We need to figure out what our exported interface on the top-level is going to be here as well.
=> Problem: index.js should export constants + native

bindings/nodejs/package.json
Solution: run `npm install --save bindings`
Solely for the node bindings
=> Problem: userland needs bindings install

src/zauth.c
PR #1398 inadvertently introduced a compile error, which didn't show up on OS X builds.
=> Fix implicit conversion error for some platforms

src/zauth.c
Solution: Add a version gate to prevent running the test on earlier ZMQ versions.
=> Problem: Testing zauth certificate metadata breaks on ZMQ < 4.1.

.travis.yml
Solution: run brew reinstall instead.
If the previous revision is already installed, instead of upgrading
(or doing nothing) brew errors out, which stops the test run.
=> Problem: brew install errors out with new version

appveyor.yml
Problem:The artifacts of the Windows CI did not contain the selftests and certificate maker.
Solution: Add them to the zip
Artifacts can be downloaded from the 'Artifacts' tab of appveyor.
https://ci.appveyor.com/project/zeromq/czmq/build/job/d2r91ienvxqedrdj/artifacts
=> Add czmq_selftest.exe and zmakecert.exe to artifacts of Windows CI

api/zcertstore.api, bindings/jni/src/main/c/org_zeromq_czmq_Zsock.c, bindings/jni/src/main/java/org/zeromq/czmq/Zsock.java, bindings/nodejs/binding.cc, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi.py, bindings/qml/src/QmlZcertstore.cpp, bindings/qml/src/QmlZcertstore.h, bindings/qml/src/QmlZsock.cpp, bindings/qml/src/QmlZsock.h, bindings/qt/src/qzcertstore.cpp, bindings/qt/src/qzcertstore.h, bindings/qt/src/qzsock.cpp, bindings/qt/src/qzsock.h, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/zcertstore.rb, bindings/ruby/lib/czmq/ffi/zsock.rb, include/zcertstore.h, src/zauth.c, src/zcertstore.c
This builds on my previous PR #1411 to allow any zcertstore loader to store state, rather than just providing a callback. This gives us two nice things:
1. It makes the interface consistent between the default disk loader and user-defined loaders
2. It allows user-defined loaders to store, for example, a connector to their certificate store, transaction IDs etc.
=> Give zcertstore loaders ability to store state

api/zcertstore.api, bindings/ruby/lib/czmq/ffi.rb, include/zcertstore.h, src/czmq_classes.h
Solution: Mark as "draft".
As discussed in #1413.
=> Problem: New zcertstore APIs were not marked as "draft".

src/czmq_classes.h
Solution: regenerate
Fixes build failure due to draft typedefs being defined twice.
=> Problem: out of date with zproject

src/ztimerset.c
only run test when building with libzmq from version 4.2
=> problem: ztimerset failing on stable libzmq release

src/zsys.c
Solution: add them to zsys_sockname in zsys.c.
=> Problem: zsys.c did not know about SCATTER / GATHER

configure.ac
Solution: re-generate autotools config from latest zproject
=> Problem: czmq fails to compile without pkg-config for autotools

api/zframe.api, include/zframe.h
This pr adds the zframe_group and zframe_set_group calls to the api model for zframe, and updates the zframe header to export these functions.
Please note I did not regenerate all of the bindings via zproject - if that's desired I can do so and send a followup PR (or someone else is welcome to).
=> Problem: zframe_set_group and zframe_group not exported

.gitignore, src/zsys.c
This is documented as a means to disable log output to the console, yet it is reset on every call to `s_log()`. This makes the code that follows immediately after the deleted code half dead:
```c
if (!s_logstream)
s_logstream = stdout;
if (s_logstream || s_logsender) {
```
as `s_logstream` can never be `NULL`. This restores rational/documented behavior.
=> Problem: zsys_set_logstream(NULL) not functional.

src/zproxy.c
Solution: Delete the test files and test directory when finishing the test.
This is an issue because `make distcheck` will fail if `make check` does
not take out the trash.
=> Problem: zproxy_test does not cleanup after itself

src/zproxy.c
After #1446 Tests were failing on older zeromq releases because on them connecting before bind in inproc transport is forbidden.
Original issue #1445
=> Test fail on older platform after fixing zproxy issue

configure.ac, include/czmq_library.h, src/zsys.c
HI,
Here the fixes for correctly compile czmq using msys2 + mingw64 gcc.
DLL_EXPORT is automatically generated by libtool. I'm using this symbol + the indication of internal compilation put in the configure.ac in order to enable dllexport or not
=> Fix compilation with mingw64 using autotools

.travis.yml
Solution: prepare travis build to use clang for android instead of gcc
To switch the android build entirely to clang there must be made a lot
of changes to the android build script.
=> Problem: travis does not compile android with clang

api/zhashx.api, bindings/nodejs/README.md, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi.py, bindings/qml/src/QmlZhashx.cpp, bindings/qml/src/QmlZhashx.h, bindings/qt/src/qzhashx.cpp, bindings/qt/src/qzhashx.h, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/zhashx.rb, doc/mkman, include/zhashx.h, src/czmq_classes.h, src/zhashx.c
Solution: Allow to supply own serializer and deserializer methods to
pack and unpack arbitrary values.
=> Problem: [zhashx] cannot (un)pack anything but string values

src/zhashx.c
VC++ doesn't handle c99 variable length arrays on the stack.
=> zhashx.cpp does not build with MSVC++

README.md, README.txt
Solution: clarify what it is used for, how to have the build system
use a different non-standard path for local installs, and how to
achieve the same result manually when it's not available.
Fixes #1475
=> Problem: README is too vague about pkg-config

src/zlist.c
Fix: add checking autofree to zlist_dup and if it is set, create autofree copy list
=> Problem: zlist_dup doesn't create copy autofree list if copied list was autofree

src/zproxy.c
Solution: delete invalid characters
Faced this error while cross compiling CZMQ with an older gcc (4.3.5). Just for the record, here is the output with the error:
```
[ 62%] Building C object CMakeFiles/czmq.dir/src/zproxy.c.o
/home/chaicko/czmq/src/zproxy.c:1: error: stray '\357' in program
/home/chaicko/czmq/src/zproxy.c:1: error: stray '\273' in program
/home/chaicko/czmq/src/zproxy.c:1: error: stray '\277' in program
CMakeFiles/czmq.dir/build.make:675: recipe for target 'CMakeFiles/czmq.dir/src/zproxy.c.o' failed
make[2]: *** [CMakeFiles/czmq.dir/src/zproxy.c.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/czmq.dir/all' failed
make[1]: *** [CMakeFiles/czmq.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
make: *** [all] Error 2
```
And the actual diff …
=> Problem: invalid characters at beginning of zproxy.c breaks compilation

include/test_zgossip.h, src/zdir.c, src/zmsg.c
Solution: change the files to reference the MPL2 license instead.
Note that the re-licensing already happened via commit eabe063, and
this is just a fix of some leftovers.
Fixes #1482
=> Problem: zdir.c, zmsg.c and test_zgossip.h are still LGPL3 licensed

.github/PULL_REQUEST_TEMPLATE.md
Solution: Use github pull request templates to make sure new users don't
miss out on reading our contribution guidelines.
(If this works out, we might consider adding those to zproject!)
=> Problem: Contribution guidelines are easily missed

.travis.yml, AUTHORS
Solution: add a workaround to reinstall libtool. Travis hasn't fixed
the issue in a month, so time for a little hack until they sort it.
=> Problem: Travis CI OSX builds are broken

README.md, README.txt
Solution: Regenerate.
This also adds CZTop (Ruby) to the list of bindings.
=> Problem: Generated README.md outdated

src/zdir.c
Solution: use readdir and protect the calls to it with a global mutex.
This is necessary because readdir has not yet been made thread safe.
It might happen in the next version of POSIX, but until then we must
ensure 2 threads never call readdir on the same directory, so a mutex
is necessary.
=> Problem: readdir_r deprecated in glibc 2.24

include/czmq_prelude.h
Solution: correctly use defined() preprocessor macro to check for
_ZMALLOC_PEDANTIC in include/czmq_prelude.h to avoid build failure
if _ZMALLOC_DEBUG is defined.
=> Problem: build failure due to missing defined()

src/zbeacon.c
Solution: Actually bind when selecting INADDR_ANY (which is 0)
=> Problem: ZBeacon does not bind to all interfaces (*) correctly.

src/zbeacon.c
Solution: Return a hostname of '*' which can be used by zsock_bind etc to bind to any interface portably.
Specifically this resolves issues on Windows with binding to 0.0.0.0 which fails.
=> Problem: Hostname for any-interface broadcast non-portable

include/czmq_prelude.h
Solution: Increase required _WIN32_WINNT to _WIN32_WINNT_VISTA
(= 0x0600).
inet_pton() (= InetPton) documentation in MSDN says:
> Minimum supported client
>   Windows 8.1, Windows Vista [desktop apps | Windows Store apps]
The current required _WIN32_WINNT is _WIN32_WINNT_WINXP (=
0x0501). inet_pton() isn't declared on Windows XP. So we need to use
_WIN32_WINNT_VISTA (= 0x600) or later to use inet_pton().
inet_pton() is used since 1dd8eb2532d8f0ddd472752308c8e0b0735fac3e
=> Problem: _WIN32_WINNT version is old to use inet_pton()

bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/zsock.rb
The Ruby generator in zproject now correctly handles socket type and
doesn't fallback treat it as a pointer anymore.
Solution: Regenerate binding.
=> Problem: Ruby binding outdated (zproject evolved)

bindings/ruby/lib/czmq/ffi.rb
I made ruby binding can be refer LIBCZMQ_PATH for looking up libczmq in https://github.com/zeromq/zproject/pull/697 and https://github.com/zeromq/zproject/pull/698 .
To available this feature I want update ruby binding.
=> Update ruby binding for referring LIBCZMQ_PATH

AUTHORS
Solution: add it. Some of the work that I do happens during working
hours and hence the copyright belongs to my employer, Brocade
Communications Systems Inc. Note this in the AUTHORS file.
=> Problem: Brocade has copyright but not in AUTHORS

src/zlist.c
This is inconsistent with its description and with behaviour of zlist_append, which returns -1 for a NULL item.
Solution: make zlist_push return -1 for a NULL item.
=> Problem: zlist_push doesn't return -1

src/zsock.c
Solution: check return code of zmsg_send, and if not 0 then destroy
the zmsg as it's created internally and owned by the API call, not
the user.
Fixes https://github.com/zeromq/czmq/issues/1529
=> Problem: zsock_vsend leaks zmsg_t on failure

src/zsock.c, src/zsock_option.gsl, src/zsys.c
Solution: see commits
I'll send the removal of v2 deprecated APIs separately.
Note the hack in zsys.c: would be nice to solve it by making the ZMQ v2/v3 socket options available, as they are currently not.
Unfortunately the way it works is that zsock_opt.gsl generates an API file, which does not have the semantics to add IFDEFS per version.
So for now a bit of a hack will do.
Suggestions welcome!
=> Problem: internal use of deprecated API

api/zsock_option.api, include/zsock.h, src/czmq_classes.h, src/sockopts.xml
Solution: move them from DRAFT to STABLE state following libzmq 4.2.0
release.
Also regenerate with make code.
I think there are a few more new in 4.2 missing?
=> Problem: new sockopt released in zmq 4.2 but still draft

src/zlist.c
Solution: Assign the source list's compare_fn to the copy list's compare_fn.
=> Problem: zlist_dup does not copy comparison function.

NEWS
Solution: add release notes mentioning deprecation of APIs,
changes in stable APIs, ABI bump, new APIs.
=> Problem: no NEWS entries for 4.0.0

CMakeLists.txt, bindings/jni/build.gradle, include/czmq_library.h, src/czmq_classes.h, src/czmq_selftest.c, src/zgossip.c
Solution: regenerate from zproject
Also call zgossip_msg_test from zgossip_test. Any better solution to run private classes tests is welcome!
Fixes https://github.com/zeromq/czmq/issues/1548
=> Problem: private symbols leaked as public

include/zsock.h
Solution: put them behind a check for DRAFT APIs as the other
definitions
=> Problem: draft sockets _checked methods always exported

src/zbeacon.c
Solution: Close invalid UDP socket when a valid interface could not be found so that we retry next time
=> Problem: zbeacon would not try to reconnect more than once

NEWS
Solution: mention ABI leakage fix, finalize changelog date
As mentioned
=> Problem: no NEWS entry for 4.0.1

.travis.yml
Solution: don't run deploy step on pyhton bindings as they don't
have any.
=> Problem: python bindings fail during release build

src/zsock.c
Solution: when CZMQ_BUILD_DRAFT_API is not set add CZMQ_PRIVATE to
their definition to avoid symbols leaking in the shared object.
=> Problem: DRAFT zsock_new_*_checked symbols leak

api/zsock_option.api, bindings/jni/src/main/c/org_zeromq_czmq_Zsock.c, bindings/jni/src/main/java/org/zeromq/czmq/Zsock.java, bindings/nodejs/README.md, bindings/nodejs/binding.cc, bindings/nodejs/binding.h, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi.py, bindings/qml/src/QmlZsock.cpp, bindings/qml/src/QmlZsock.h, bindings/qt/src/qzsock.cpp, bindings/qt/src/qzsock.h, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/zsock.rb, include/zsock.h, src/sockopts.xml, src/zsock_option.gsl, src/zsock_option.inc
Solution: rework the sockopts compatibility layer to generate a
runtime check together with the build time check. In case the runtime
check fails, print an error stating what the minimum required is vs
the runtime version. It could be argued that an assert should be used
instead, but this follows the same principle as the existing
implementation where options not available at buildtime are compiled
to simply return 0 and be no-ops, rather than asserting.
Rework the sockopts.xml layout to let the options of each zmq version
be grouped together in different and independent blocks to allow mix
and match. Introduce a major_removed element to indicate in which
version an option has been removed, to allow a finer granularity in
the build time and run time checks.
Fixes …
=> Problem: zsock options could be available at build time but not at runtime

api/zsock_option.api, bindings/jni/src/main/java/org/zeromq/czmq/Zsock.java, bindings/nodejs/README.md, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi.py, bindings/qml/src/QmlZsock.cpp, bindings/qml/src/QmlZsock.h, bindings/qt/src/qzsock.cpp, bindings/qt/src/qzsock.h, bindings/ruby/lib/czmq/ffi/zsock.rb, builds/msvc/vs2010/libczmq/libczmq.props, builds/msvc/vs2012/libczmq/libczmq.props, builds/msvc/vs2013/libczmq/libczmq.props, builds/msvc/vs2015/libczmq/libczmq.props, doc/Makefile.am, doc/zloop.doc, doc/zloop.txt, doc/zpoller.doc, doc/zpoller.txt, doc/zsock.doc, doc/zsock.txt, include/zsock.h, src/zsock_option.gsl
Solution: for each option state the required minimum (and maximum if
applicable) version of libzmq.
=> Problem: zsock options API does not document libzmq requirements

src/zhash.c, src/zsock.c
Solutions: Where I had issues, root out the possible rootcauses, and improve debugging (in case others have similar issues on their platforms)
=> Problem: zsock.c tests can be unreliable in 32-bit builds

examples/security/grasslands.c, examples/security/hello.c, examples/security/ironhouse.c, examples/security/ironhouse2_v2.c, examples/security/stonehouse.c, examples/security/strawhouse.c, examples/security/woodhouse.c
The current examples in examples/security do not compile with the current version of CZMQ.
I fixed all samples but the ironhouse2-sample which was using zthread. I'm not familiar with zactor,yet. Therefore I just renamed the file to ironhouse2_v2.c to indicate this file is still based on API v2.
=> Fixed examples to work with CZMQ API v3

bindings/ruby/lib/czmq/ffi.rb
Because :uint64_t type is used. It doesn't exist in ffi gem. We should use :uint64 instead. :uint64 exists in ffi gem.
It has been fixed by zeromq/zproject#771.
Solution: Regenerate Ruby bindings.
Fix #1581
=> Problem: Ruby bindings don't work on Windows

README.md, api/zhash.api, api/zhashx.api, bindings/jni/src/main/java/org/zeromq/czmq/Zhash.java, bindings/lua_ffi/czmq_ffi.lua, bindings/nodejs/README.md, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi.py, bindings/qml/src/QmlZhash.cpp, bindings/qml/src/QmlZhash.h, bindings/qt/src/qzhash.cpp, bindings/qt/src/qzhash.h, bindings/ruby/lib/czmq/ffi/zhash.rb, bindings/ruby/lib/czmq/ffi/zhashx.rb, include/zhash.h, include/zhashx.h, src/zhashx.c
Solution: update documentation and regenerate
Fixes https://github.com/zeromq/czmq/issues/1032
=> Problem: zhash_autofree implies the value must be a string, but the documentation does not mention this

include/czmq_prelude.h, src/zuuid.c
Solution: add define and rework zuuid library detection and usage. If libuuid is available and detected just use it without checking for the OS.
=> Problem: debian/kFreeBSD build broken

src/zsys.c
Solution: decrement count of open sockets if it manages to close them
from the internal list.
The total count of open sockets might go up without a socket being
appended to the list, but if a socket is appended to the list then
count is always incremented. So it's safe to decrement the count as
sockets are popped out of the list and closed.
This increases the chances that a clean exit is achieved even with
dangling sockets.
=> Problem: zsys_shutdown does not call zmq_term when it closes sockets

src/zpoller.c
Solution: Compare before and after sizes of poll set instead.
This should improve performance of #1594.
I hope this is okay. Still not that experienced in C. 😅 
Can't compile it due to:
```
$ make
Making all in doc
asciidoc -d manpage -b docbook -f ./asciidoc.conf \
-aczmq_version=4.0.3 -ozmakecert.xml zmakecert.txt
xmlto man zmakecert.xml
xmlto: /Users/paddor/dev/c/czmq/doc/zmakecert.xml does not validate (status 3)
xmlto: Fix document syntax or use --skip-validation option
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
/Users/paddor/dev/c/czmq/doc/zmakecert.xml:2: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
D DocBook XML V4.5//EN" …
```
=> Problem: list of readers is scanned unnecessarily

src/zpoller.c
Solution: in zpoller_remove, compare the size before and after
removing the element with zlist_size, rather than the self poll_size,
as the latter only gets updated when the zpoller list is rebuilt, so
unless zpoller_wait is called it will not change
=> Problem: zpoller_test fails without ZMQ_POLLER

src/zsys.c
Problem: on windows, killing czmq console application generates a trap
Solution: add handling of CTRL_CLOSE_EVENT in zsys.c (s_handler_fn_shim)
(this can be tested with zyre's zpinger application)
=> handle CTRL_CLOSE_EVENT

CMakeLists.txt, appveyor.yml, src/czmq_selftest.c
problem : unit tests do not run on appveyor
solution :
the issue is that the exe and dlls were not on the same folder, so I propose to build czmq_selftest and zmakecert in the same folder as the dlls. BTW, this makes debugging wihtin visual studio much easier.
The explicit call to zsys_shutdown is also required.
Please note that the solution propose here implies the change in a generated file (CMakeLists.txt) so the real fix should be in zproject I guess, so this may not be merged "as is"
=> Fix win32 build

src/zbeacon.c
problem : 
on windows system, in exotic languages, the interfaces names can be complex, include spaces and special characters, making the use of the variable ZSYS_INTERFACE for network interface selection difficult.
solution:
allow the ZSYS_INTERFACE variable to be a single digit, selecting the i-th number interface of the system.
keep the existing behaviour for other values. 
can be tested/validated with zbeacon self test
=> ZSYS_INTERFACE variable can be a single digit

src/zproxy.c
solution : replace ipc with inproc (only for windows)
=> problem : zproxy self test fails under windows

src/zdir.c
fix : rework the assert macros to avoid calls within assert.
=> problem : zdir test fails on windows/release

api/zsock_option.api, include/zsock.h, src/sockopts.xml, src/zsock_option.gsl, src/zsock_option.inc
Solution: keep the public API stable regardless of the libzmq version
available at build time.
All the zsock_* options functions will always be available, but with
both build time and runtime checks.
This ensure full transparent compatibility with all versions of
libzmq, and avoids API breakages during rebuilds.
Achieved by removing the global ifdefs around the libzmq version and
by avoiding redefining the same option for different versions in
sockopts.xml.
Since libzmq does strict type size enforcement we can't simply cast
up or down. Introduce new attributes "major_changed" and "type_new"
to signal when an option type changes and to what.
Fixes #1603
=> Problem: public API/ABI changes depending on libzmq version

api/ziflist.api, bindings/jni/src/main/c/org_zeromq_czmq_Ziflist.c, bindings/jni/src/main/java/org/zeromq/czmq/Ziflist.java, bindings/lua_ffi/czmq_ffi.lua, bindings/nodejs/README.md, bindings/nodejs/binding.cc, bindings/nodejs/binding.h, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi.py, bindings/qml/src/QmlZiflist.cpp, bindings/qml/src/QmlZiflist.h, bindings/qt/src/qziflist.cpp, bindings/qt/src/qziflist.h, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/ziflist.rb, include/ziflist.h, src/czmq_classes.h, src/zbeacon.c, src/ziflist.c, src/zsys.c
Solution: see commits
Given the output would change I added 2 new draft ziflist_new_ipv6 and ziflist_reload_ipv6 to keep backward compatibility.
Not implemented for Windows, help needed!
=> Problem: ziflist does not support IPv6

include/czmq_prelude.h, include/zsys.h, src/zbeacon.c, src/zsys.c
Solution: see commits
Implement support for IPv6 multicast, using ff02::1 as the default address which provides more or less the equivalent of IPv4 broadcast.
Note the hack in the last commit: due to what I think it's a Linux specific quirk it's not possible to receive v6 multicast if the socket is bound to anything other than inaddr_any, which breaks Zbeacon since the source address will be randomly picked. So I had to use 2 UDP sockets, one for sending and one for receiving.
Tested on Linux with zpinger and zbeacon_tester from zyre between a desktop, a raspberry pi 2 running Debian armv7 and a raspberry pi 3 running Fedora arm64.
Help testing on osx and on more machines with zyre would be very welcome!
=> Problem: Zbeacon does not support IPv6

builds/msvc/vs2010/build.bat, builds/msvc/vs2010/czmq.import.props, builds/msvc/vs2010/libczmq/libczmq.import.xml, builds/msvc/vs2010/libczmq/libczmq.vcxproj, builds/msvc/vs2012/build.bat, builds/msvc/vs2012/czmq.import.props, builds/msvc/vs2012/libczmq/libczmq.import.xml, builds/msvc/vs2012/libczmq/libczmq.vcxproj, builds/msvc/vs2013/build.bat, builds/msvc/vs2013/czmq.import.props, builds/msvc/vs2013/libczmq/libczmq.import.xml, builds/msvc/vs2013/libczmq/libczmq.vcxproj, builds/msvc/vs2015/czmq.import.props, builds/msvc/vs2015/libczmq/libczmq.import.xml, builds/msvc/vs2015/libczmq/libczmq.vcxproj
Solution: expose the optional configuration using a property in `czmq.import.props`. Add the option to VS UI in `libczmq.import.xml`. Use the condition in `libczmq.vcxproj` to include draft classes only when option is true.
To use the switch, pass `/p:Option-draftapi=[false|true]` to msbuild. Example from `build.bat`:
`msbuild /m /v:n /p:Configuration=DynDebug /p:Platform=Win32 /p:Option-draftapi=false %packages% %solution% %target% >> %log%`
Probably these changes should go to zproject in someway, as the involved files have the "THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY" comment.
=> Problem: windows build via build.bat does not have enable/disable draft api switch

include/zsubproc.h, src/zsp.c, src/zsubproc.c
Solution: use ifdefs more aggresivelly and convert more functions to be stubs only on Windows.
=> Problem: zsubproc broke Windows builds of czmq

include/zsubproc.h, src/zsubproc.c
Solution: fix make distcheck, binary is searched in _build/../
@sappo @bluca @jimklimov - maybe we should fix this on zproject level. For instance export some special variable pointing to source directory for distcheck or so.
So the code will be way more simple. Of course FOO is a stupid name, it should be ZFOO or ZSUSHI at least ;-)
#include <czmq.h>
int main () {
// done in selftest binary
assert (getenv ("FOO"));
char *zsp = zsys_sprintf ("%ssrc/zsp", getenv ("FOO"));
zsys_info ("zsp=%s", zsp);
zstr_free (&zsp);
}
=> Problem: Travis CI fails

src/zbeacon.c
Solution: do not use AI_V4MAPPED on those systems as it's not
supported
Fixes #1641
=> Problem: getaddrinfo in zbeacon fails on Android and FreeBSD

src/zbeacon.c
Sending to INADDR_BROADCAST on Windows only results in a single packet being sent over the interface with the highest metric.
This results in nodes not being seen on all interfaces when using the any ("*") interface, metric can be observed using the command 'route print'
Solution: SIO_GET_INTERFACE_LIST offers a cheap way of enumerating interfaces available to a specific socket so a packet can be sent per interface. Profiling shows this method at 0.006ms per invokation against 0.5ms for GetIpAddrTable meaning that this can be used on every beacon send instead of caching the results.
=> Problem: Windows only sends on one interfaces with INADDR_BROADCAST set (interface option "*")

src/zbeacon.c
=> Problems: static helper not declared as static, trailing whitespace

api/zproc.api, bindings/jni/src/main/c/org_zeromq_czmq_Zproc.c, bindings/jni/src/main/java/org/zeromq/czmq/Zproc.java, bindings/lua_ffi/czmq_ffi.lua, bindings/nodejs/README.md, bindings/nodejs/binding.cc, bindings/nodejs/binding.h, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi.py, bindings/qml/src/QmlZproc.cpp, bindings/qml/src/QmlZproc.h, bindings/qt/src/qzproc.cpp, bindings/qt/src/qzproc.h, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/zproc.rb, include/zproc.h, src/zproc.c
Solution: see pull requests
In fact code is way more straightforward than before, because argv/env are built right before execve and not passed from zproc_run to actor and pipe handler.
=> Problem: zproc_run method can't be expressed as zproject API model

src/zproc.c, src/zsp.c
Solution: kill zsp outside of main loop, so code deal with stdout socket
only
cc: @sappo
=> Problem: zproc unit test is too complicated

include/zsys.h, src/zsys.c
closes https://github.com/zeromq/czmq/issues/1659.
First PR here. I've read and agree to C4.1.
This change requires (some) version change, because code that depends on this fix must have a way to check for it. Not sure how new minor/patch versions are handled in the project.
Follow up to #1649 (as it turns out), extending it to reset all global state, not just dangling pointers.
=> Problem: zsys_init() + fork() causes undefined behaviour

include/zsys.h, src/zsys.c
Solution: hide it behind DRAFT flag for now. We have to be careful in
not changing public API freely, but in a controlled and safe manner.
Also remove inline to avoid compiler errors about unused function,
and remove redundant resets.
Followup on #1660
=> Problem: zsys_reset changes public API side effects

include/zsys.h, src/zsys.c
Solution: reset state if shutdown was clean. Until #1649, no code could rely on behavior wrt global state on a zsys shutdown+init (restart), because any attempt to call zsys_init() after zsys_shutdown() would assert and #1649 has not been part of of any official release yet , so there's no reason to punt on this for reasons of back-compat.
followup to  #1649 , #1660 , #1661
=> Problem: Global zsys state not cleared after clean zsys_shutdown()

README.md, include/zsys.h, src/zsys.c
Solution: add them
These have been in libzmq since 4.1.x but there was no way to set them via CZMQ. Also regenerate the README.
I didn't add them as DRAFT since there's really nothing to change in the public API, libzmq takes an int as a parameter so there is no room for change anyway
=> Problem: no zsys APIs for thread scheduling context options

src/zbeacon.c
Solution: check self->udpsock_send which is actually used to send
rather than self->udpsock whcih is used just to receive
=> Problem: zbeacon checks wrong UDP socket before send

src/zframe.c, src/zmsg.c
Solution: implement additional checks to bring them up to speed
They are marked as deprecated, but until they are provided they should be fully supported
=> Problems: zmsg/zframe_recv_nowait out of date with vanilla versions

src/ziflist.c
Problem: cannot build on msvc for a simple syntax error
Solution: prefixing 'struct' on 'sockaddr_in' struct
=> Fix compile error 'sockaddr_in': undeclared identifier on msvc

src/zhashx.c
Solution: freen() the old self->items before reassigning to the newly allocated smaller one
=> Problem: zhashx_purge() seems to leak when shrinking

bindings/jni/src/main/java/org/zeromq/czmq/Zcert.java, bindings/jni/src/main/java/org/zeromq/czmq/Zconfig.java, bindings/jni/src/main/java/org/zeromq/czmq/Zframe.java, bindings/jni/src/main/java/org/zeromq/czmq/Zhash.java, bindings/jni/src/main/java/org/zeromq/czmq/Zhashx.java, bindings/jni/src/main/java/org/zeromq/czmq/Zmsg.java, bindings/jni/src/main/java/org/zeromq/czmq/Zsock.java, bindings/jni/src/main/java/org/zeromq/czmq/Zuuid.java
Solution: Regenerate from a patched zproject that makes them so
This is the change created by https://github.com/zeromq/zproject/pull/910
as a fix for https://github.com/zeromq/zproject/issues/909
=> Problem: singleton JNI methods aren't static

api/zsys.api, include/zsys.h, src/zsys.c
Solution: keep it off the zproject API definition for now, as it's
never been there in the first place, and define it manually with
ssize_t as the return value instead.
=> Problem: API compatibility broken for zsys_file_size

api/zhashx.api
two corrections on descriptions in zhashx
one change is to correct an error in description for set_key_hasher.
bluca told me on IRC how it has to be right.
other is an addition to the description of set_key_comparator function
to eliminate possible confusion what the callback function has to return.
=> changed description of 2 zhashx functions

CMakeLists.txt, api/zactor.api, bindings/lua_ffi/czmq_ffi.lua, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi/_cdefs.inc, bindings/python_cffi/czmq_cffi/cdefs.py, bindings/qml/src/QmlZactor.cpp, bindings/qml/src/QmlZactor.h, bindings/qt/src/qzactor.cpp, bindings/qt/src/qzactor.h, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/zactor.rb, include/zactor.h, src/zactor.c
Solution: add a custom destructor function callback, which overrrides default
zmsg_t with $TERM by own message format. With this patch it's possible to use
custom messages built by zproto_codec_c without converting them from/to zmsg_t.
Note the actor itself MUST handle new termination message, otherwise it won't be stopped
=> Problem: can't use zproto non-virtual API for zactor pipe

README.md, api/zframe.api, bindings/lua_ffi/czmq_ffi.lua, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi/_cdefs.inc, bindings/python_cffi/czmq_cffi/cdefs.py, bindings/qml/src/QmlZframe.cpp, bindings/qt/src/qzframe.cpp, bindings/ruby/lib/czmq/ffi/zframe.rb, include/zframe.h, src/zframe.c
zframe_meta returns the value from zmq_msg_gets directly and according
to http://api.zeromq.org/4-2:zmq-msg-gets
The zmq_msg_gets() function shall return the string value for the
property if successful. Otherwise it shall return NULL and set errno to
one of the values defined below. The caller shall not modify or free the
returned value, which shall be owned by the message. The encoding of the
property and value shall be UTF8.
=> problem: zframe_meta documentation is incorrect

src/zauth.c
problem: zauth tests do not check User-Id metadata
Solution: update the PLAIN and CURVE tests to fetch and verify the
User-Id metadata set by ZAP
problem: User-Id field in zap response is not populated.
According to ZAP spec:
user id: this MAY provide the user identity in case of a 200 status, for
use by applications. For other statuses, it SHALL be empty.
Solution:  This adds a char pointer in the zap request struct that can
point to the the username, client_key, or principal fields.
With this change zframe_meta(frame, "User-Id") returns the public key
for a connection.  This enables a use case where you have a long lived
connection authenticated by a key or password and want to verify that the
user/key still exists.
zframe_t *frame = zframe_recv(server);
const char *user_id = …
=> problem: User-Id field in zap response is not populated

api/zcertstore.api, include/zcertstore.h, src/zcertstore.c
solution: add zcertstore_certs method that returns a zlistx of certs
This may not be 100% right yet - I'm not sure how to regenerate the bindings and documentation.  The goal is to be able to do something like this:
zcert_t *cert;
zlistx_t *certs = zcertstore_certs(certstore);
cert = (zcert_t *) zlistx_first(certs);
while (cert) {
char *endpoint = zcert_meta (cert, "endpoint");
if(endpoint) {
fprintf(stderr, "Connect to %s using %s\n", endpoint, zcert_public_txt(cert));
}
cert = (zcert_t *) zlistx_next(certs);
}
zlistx_destroy(&certs);
That way an application won't require any configuration aside from a certstore path.  This could also be used to find the cert in a certstore that has the private key as well.
=> problem: no way to loop over all certs in a zcertstore

api/zcertstore.api, bindings/jni/src/main/java/org/zeromq/czmq/Zcertstore.java, bindings/lua_ffi/czmq_ffi.lua, bindings/nodejs/README.md, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi/_cdefs.inc, bindings/python_cffi/czmq_cffi/cdefs.py, bindings/qml/src/QmlZcertstore.cpp, bindings/qml/src/QmlZcertstore.h, bindings/qt/src/qzcertstore.cpp, bindings/qt/src/qzcertstore.h, bindings/ruby/lib/czmq/ffi/zcertstore.rb, include/zcertstore.h, src/czmq_classes.h, src/zcertstore.c
solution:
zcertstore configures itself with a destructor that calls
zcert_destroy.  zhashx_values copies this destructor by default, causing
zlistx_destroy on the returned list to incorrectly destroy the
certificates.  To fix this the destructor must be disabled on the
zlist_x before it can be destroyed.
=> problem: zcertstore_certs was broken

src/Makemodule.am, src/zsys.c
Solution: augment the timing-dependent portion of code and test with optional verbosity (requested privately from tests, invisible for ordinary consumers)
Context:
As discussed on IRC, I have this test failing in valgrind of czmq-master built as part of a larger project on Travis. I could not reproduce the issue isolated from that build, nor in local rebuilds, so its heaviness and/or Travis virtualization may be a contributing factor (this test relies on speed that a recently created file is "young", so lags are fatal). Curiously, non-memcheck builds against czmq-master, as well as any sort of builds against our legacy baseline fork of czmq-v3.0.2 (where these routines seem to be same as in master) do not fail the same tests in Travis.
In …
=> Problem: can not see why zsys_test fails

bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java
Solution: do not use a reserved Java keyword "interface" in Zsys.java; rename function to getInterface()
Note: maybe there should be some place to document this modification and different behavior compared to other bindings. This change likely breaks no consumers because previous code never passed the build since introduction, per Travis build history (see `git diff f05c010 1042d8f` for change between green and red states). Probably the binding code is generated from the C code - if so, the parser script should also be amended to produce this exclusion and perhaps comment upon re-generations.
=> Problem: CZMQ master build fails in JNI binding

src/zsys.c
Solution: mark it with static
Follow-up for #1718 per review
=> Problem: private s_zsys_file_stable() should not be exported

src/Makemodule.am, src/zfile.c
Solution: apply the logging solution used in zsys_test() to trace zfile_test() in the timing-dependent section
Yet another follow-up to #1718 - that sort of assert explodes in `zfile_test` too
=> Problem: zsys_file_stable sometimes explodes in zfile tests

include/czmq_prelude.h
Solution: add the PRIi* to czmq_prelude.h
NOTE: Before merging, wait for AppVeyor Windows tests to pass
=> Problem: MSVS does not have PRIi64

src/zsys.c
Solution: Drop dir in zsys_test(). It seems safe to just do so, no extra checks on presence are needed.
=> Problem: zsys_test can fail if old run artifacts are present

api/zcert.api, bindings/jni/src/main/c/org_zeromq_czmq_Zcert.c, bindings/jni/src/main/java/org/zeromq/czmq/Zcert.java, bindings/lua_ffi/czmq_ffi.lua, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi/_cdefs.inc, bindings/python_cffi/czmq_cffi/cdefs.py, bindings/qml/src/QmlZcert.cpp, bindings/qml/src/QmlZcert.h, bindings/qt/src/qzcert.cpp, bindings/qt/src/qzcert.h, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/zcert.rb, include/zcert.h, src/czmq_classes.h, src/zcert.c
solution: create zcert_new_from_txt function that takes in keys as text and generates a cert (instead of just from binary or disk)
added as a DRAFT function for now... thought about modifying new_from but wasn't sure if that would potentially break things for others...
=> problem: missing zcert_new_from_txt function 

Vagrantfile, bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java, ci_build.sh, src/Makemodule.am, src/zfile.c, src/zsys.c
Solution: refactor the selftests to use selftest-rw rather than builddir, and to clean up with noise (if some dirt blocks the test run).
=> Problem: zfile and zsys tests do not use selftest-rw dir

src/zframe.c, src/zsock.c
Solution: bind to a random port and then retrieve it to avoid test
failures when the port is already occupied on busy machines
Fixes #1726
=> Problem: unit tests bind to hard-coded TCP ports

include/czmq_prelude.h, src/test_zgossip.c, src/zhashx.c
Solution: explicitly floorf() the generated value before converting to int, just in case
=> Problem: randof() strikes again

api/zsys.api, bindings/jni/src/main/c/org_zeromq_czmq_Zsys.c, bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java, bindings/lua_ffi/czmq_ffi.lua, bindings/nodejs/README.md, bindings/nodejs/binding.cc, bindings/nodejs/binding.h, bindings/python/czmq/_czmq_ctypes.py, bindings/python/test.py, bindings/python_cffi/czmq_cffi/_cdefs.inc, bindings/python_cffi/czmq_cffi/cdefs.py, bindings/qml/src/QmlZsys.cpp, bindings/qml/src/QmlZsys.h, bindings/qt/src/qzsys.cpp, bindings/qt/src/qzsys.h, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/zsys.rb, include/zsys.h, src/czmq_classes.h, src/zdir.c, src/zfile.c, src/zsys.c
Solution: Document the analysis of why checking for (age>1000) when we account in values rounded to thousands is misleading, propose better solutions and an improvement for current implementation.
This takes off from discussion in IRC.
=> Problem: zsys_file_stable() check for (age>1000) is weak

include/czmq_prelude.h
Solutions: in czmq_prelude.h randof() :
* make sure to use RAND_MAX only where available;
* make more effort to multiply NUM by a factor of less than 1.0 - limit the chosen random function result by chosen maximum minus one (remainder of...) in all cases, and parenthesize calculation of the "0...<1" factor to avoid overflows etc.
* do not calculate the random-factor with large numbers like UINT32_MAX or RAND_MAX (big on e.g. Linux-64bit), because either `float` can not discern these values plus-minus several discrete levels at all, or (in experiment with `double`) the resulting factor has too many nines and multiplication yields "num.0000000" anyway. Constrain this to smaller numbers, use UINT16_MAX which passed the artificial tests ok.
Details:
During builds of previous PR and master …
=> Problem: once in a few million runs, randof() still lies

api/zsys.api, bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java, bindings/lua_ffi/czmq_ffi.lua, bindings/nodejs/README.md, bindings/python/czmq/_czmq_ctypes.py, bindings/python/test.py, bindings/python_cffi/czmq_cffi/_cdefs.inc, bindings/python_cffi/czmq_cffi/cdefs.py, bindings/qml/src/QmlZsys.cpp, bindings/qml/src/QmlZsys.h, bindings/qt/src/qzsys.cpp, bindings/qt/src/qzsys.h, bindings/ruby/lib/czmq/ffi/zsys.rb, include/zsys.h, src/czmq_classes.h, src/zdir.c, src/zfile.c, src/zsys.c
Solutions:
* use longer default timeout that should suffice for laggy hosts and OSes (note: so perhaps also more incentive to tune it via `configure` for host OSes with better known characteristics and/or extended stat-struct fields with better timestamp resolution); 
* use even longer poll-timeouts in zdir_test() waiting for FS changes to be detected
=> Problem: File stable timeout tests still fail

.gitattributes, .gitignore, src/zproc.c, src/zsp.c
Solution: figure out and unravel the draft :)
Note: this only pops up in builds with `--enable-drafts=yes` as `zproc` is still experimental.
Merge criteria: the issue is fixed if such errors are not seen in a run:
````
* zproc: W: (czmq_selftest) 17-08-03 17:13:56 cannot detect zsp binary, src/zsp does not exist
SKIPPED (zsp helper not found)
````
but rather success is logged:
````
* zproc: OK
````
=> Problem: zproc_test() can not find its zsp helper

src/zdir.c, src/zfile.c, src/zgossip_msg.c, src/zproc.c, src/zsys.c
Solution:
* figure out and unravel the draft :)
* fix a side effect of zsys tests (changed CWD)
* make this fix compile on Windows too
Continuation of #1736
Note: this only pops up in builds with `--enable-drafts=yes` as `zproc` is still experimental, and only against ZMQ4+.
Merge criteria: the issue is fixed if such errors are not seen in a run:
````
* zproc: W: (czmq_selftest) 17-08-03 17:13:56 cannot detect zsp binary, src/zsp does not exist
SKIPPED (zsp helper not found)
````
but rather success is logged:
````
* zproc: OK
````
=> Problem: zproc_test() still can not find its zsp helper

examples/security/ironhouse2.c
* Drop zctx_t (hidden/encapsulated in API v4)
* Use zsock which replaces zsocket (gone in API v4)
* Use zactor which replaces zthread (gone in API v4)
* Use zactor_t in place of zauth_t (gone in API v4)
* Use asserts where possible to catch errors as early as possible
```
```
git push -f
In case you already merged …
=> Fix examples/security to compile with API v4

include/czmq_prelude.h
Solution: refer to the chosen random() vs. rand() function to use the limiting value (RAND_MAX applies to rand(), and random() usually returns a 32-bit value from HW or kernel).
Also some other fixes of mostly cosmetic value.
=> Problem: RAND_MAX can get used when ZSYS_RANDOF_FUNC==random()

src/zproxy.c
Solution: send with ZFRAME_DONTWAIT when expecting a send failure, as
the pipe might not exist which means the send, without a timeout, will
get stuck forever waiting for a pipe to appear.
=> Problem: zproxy still hangs on slow architectures

src/zpoller.c
Solution: to support the change in the DRAFT zmq_poller API, check for
EAGAIN too.
See: https://github.com/zeromq/libzmq/issues/2713
Note that I've kept the ETIMEDOUT as well for now, to help users with older versions, even if it's a DRAFT api the cost is very low.
=> Problem: zpoller checks for ETIMEDOUT instead of EAGAIN in zmq_poller

src/zauth.c, src/zproxy.c
Solution: always set it for all auth types. This is required by the
ZAP protocol, and previously libzmq let it slip, but not anymore.
More precisely, always set the domain for PLAIN auth and for the
negative CURVE test.
=> Problem: zauth and zproxy tests do not set ZAP domain

src/zgossip.c, src/zgossip_engine.inc
solution: re-factor how zap domains are set, (less in _engine.inc), set a default "global" context if none is set when BIND is called.
=> problem: zap domain not being set in gossip

src/zproxy.c
when developing using vagrant and virtualbox- it maps your checked out directory to /vagrant so you can test within the vm (virtualbox shared folder effectively). for whatever reason, ipc pipes get funny when trying to run/link within this shared directory.
solution: check to see if we're running the test as the `vagrant` user- if so use /tmp as the ipc backend for proxy tests instead of the `pwd` which is typically a shared folder and vbox tends to disallow by default.. this fix is very specific to vagrant unix systems, but vagrant + vbox very much aid in czmq development imo.
(this has been bugging me for a while...)
=> problem: ipc proxy tests fail when using vagrant/virtual box

src/zauth.c, src/zcert.c, src/zcertstore.c, src/zconfig.c, src/zdir.c, src/zdir_patch.c, src/zfile.c, src/zproxy.c, src/zsys.c
Solution: remove comments generated by zproject, don't assert const chars,
remove unused variables and remove comments about C++ from C project. Only
relevant code is a part of generated documentation now.
=> Problem: copy and paste text found in czmq manual pages

api/zfile.api, include/zfile.h, src/czmq_classes.h, src/zfile.c
Solution: fixed implementation of zfile_tmp to use mkstemp. Now it hall be secure.
=> Problem: can't handle temp files in tests easily

src/zproxy.c
Solution:
1.) Move them to appropriate place in the test
2.) It does not make a sense to cat two constant strings using
sprintf. Simply declare them with a content they should have.
@bluca I'd like to trigger Travis on an another PR.
=> Problem: zproxy_test does construct variables the hardest way

src/zhashx.c
Solution: don't treat pointer as Boolean, instead test it against NULL.
=> Problem: VC++ warning C4550 when implicit cast of fn ptr to bool.

src/zfile.c
Solution: use only explicitly ANSI Windows APIs. Also fix style errors.
There is no point in using Unicode or conditionally-Unicode (TCHAR) APIs in most cases as zeromq does not utilize wchar_t or TCHAR string types. In order to be Unicode capable in Windows zeromq should implement [UTF8 Everywhere](http://utf8everywhere.org).
=> Problem: inconsistent use of TCHAR will break non-unicode VC++.

include/czmq_library.h, include/czmq_prelude.h
Fix autotools build on Cygwin failing due to:
- O_BINARY symbol redefinition in include/czmq_prelude.h
- __attribute__ ((visibility ("hidden"))) not supported by Windows executables.
=> Fix autotools build on Cygwin

src/ziflist.c
Solution: Avoid calling getnameinfo() for netmasks without a sa_family
by skipping the interfaces with netmask.sa_family = 0.
Closes #1802.
=> Problem: ziflist selftest crashes if vbox VM is running

Jenkinsfile, project.xml
Solution: tune the recipe so it passes... renamed test dir (unstash in another agent) complicates things for libtool... Hope to hack a cleaner solution, ultimately generatable with zproject, at some point. But so far a more important value would be for this to just work - even if suboptimally.
=> Problem: Jenkinsfile does not pass distcheck etc.

CMakeLists.txt
Problem: Not able to configure static library build
https://github.com/zeromq/czmq/issues/1811
Solution: 
Changes to zproject allow to configure static and shared library builds.
This commit includes a new generated CMakeLists.txt file.
Tested on Linux and Windows.
=> New CMakeLists.txt with static/shared library support generated with zproject

CMakeLists.txt
Because of compatibility issues, versioned DLL library naming had to be removed.
Hopefully appveyor tests succeed again.
Tested on Linux and Windows.
=> Removed versioned library naming

include/czmq_prelude.h
Solution: Add OpenBSD to existing list of BSDs for correct
header inclusion
=> Problem: uuid header not correctly included on OpenBSD

api/zconfig.api, include/zconfig.h, src/czmq_classes.h, src/zconfig.c
not just root.
Previously a method `zconfig_remove` had been created that removes just
the subtree (all children) of the selected node, which is confusing.
SOLUTION:
* Rename `zconfig_remove ()` -> `zconfig_remove_subtree ()`
* Use name `zconfig_remove` for the _new_ method
* Implement `zconfig_remove ()`
* Write test for `zconfig_remove ()`; Extend test for `zconfig_remove_subtree ()`
=> PROBLEM: Need to remove any node and subtree

Jenkinsfile, project.xml
Solution: option use_test_retry>1 can help proceed with development while we figure out how to make selftests robust in all circumstances; also update Jenkinsfile via zproject (and reapply currently needed manual fixes)
WIP note: merge this only if it does pass green in all tests ;)
=> Problem: some tests fail randomly

src/zproc.c
Solution: guessing that the randomly chosen and hardcoded timeout (800msec) was too short in some cases, allow a longer one overall and check if it expired in 800-msec increments.
Please do review the changeset - to weed out logical mistakes and my misconceptions, if any ;)
=> [WIP] Problem: zproc selftests sometimes fail

src/zproc.c
Solution: hide recently added zsys_debug() calls behind the verbose option
=> Problem: zproc selftest too verbose by default now

include/czmq_prelude.h, src/zuuid.c
Problem: zuuid.c on v4.1.0 is broken on FreeBSD 11.1-STABLE
Solution: apply fixes in this pull request for include/czmq_prelude.h and src/zuuid.c
* This fix works on FreeBSD 10.4-RELEASE and 11.1-RELEASE, 11.1-STABLE
* Forcefully define HAVE_UUID in czmq_prelude.h if FreeBSD
- FreeBSD has the stock UUID library, but it's not -luuid, it's in -lc, so HAVE_UUID is not defined during configure
* Skip code in zuuid.c assuming uuid_generate(2) if FreeBSD
- FreeBSD does not have uuid_generate(2) (it's Linux specific); use existing code for FreeBSD instead
See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=224853 for the details
=> Fix zuuid.c build error on FreeBSD

src/zproc.c
Solution: use _NSGetEnviron () routine to get environ variable on OSX
I've no access to OSX, someone should check if it builds and works before merging. Should fix #1834
=> Problem: can't build czmq on osx

src/Makemodule-local.am
Until now, it is possible to build from scratch (or remove `src/zsp`) and end up with skipped zproc tests because the helper is not found. Not anymore (if it is enabled).
=> Makemodule-local.am : require ZSP helper available before check recipes

src/zproc.c
Solution: implement zproc_new and zproc_destroy for win
=> Problem: zproc is not implemented on windows

src/zconfig.c
Solution: Add the support, count tab as 1 level / 4 spaces.
Signed-off-by: Jana Rapava <janarapava@eaton.com>
Forwarded-by: Jim Klimov <evgenyklimov@eaton.com>
=> Problem: We would like to use tabs in ZPL configs.

src/zconfig.c
Reverts zeromq/czmq#1842
Two reasons:
1. PR does not solve a problem. You can set your favourite editor to expand tabs.
2. The [ZPL RFC specification](https://rfc.zeromq.org/spec:4/ZPL/) clearly states that `Hierarchy is signaled by indentation, where a child is indented *4 spaces* more than its parent.`
=> Revert "Problem: We would like to use tabs in ZPL configs."

src/zproxy.c
streq(getenv(envvar), ...) segfaults when the envvar variable does not exist because the return value of getenv is 0
Extend the if condition with a short-circuit check of the getenv's return value 
Fixes zeromq/czmq#1844
=> Fix segfault when no USER environment variable exists

include/zproc.h, src/zproc.c
Solution: create new execpair zeromq pair, which is used to make
zproc_run synchronized with internal actor. This is the best
approximation of making sure zproc_run ends just before
execve/CreateProcess is called.
=> Problem: zproc_run returns before execve is called

include/czmq_prelude.h
Same issue here: https://github.com/flavio/qjson/issues/26
=> Don't define strtoull and atoll on MINGW environment

src/zsys.c
Solution: don't ifdef out the implementation of DRAFT APIs, the
visibility is handled by the compiler
=> Problem: non-draft build broken by ifdefs

.travis.yml
solution: merge zproject checks from zyre/.travis.yml into czmq/.travis.yml
ironically the zproject check currently fails because of what looks like a manual work-around in the java bindings? (maybe that's a good thing to remind us it's there?)
https://travis-ci.org/wesyoung/czmq/jobs/341938641
=> problem: travis doesnt check zproject

src/zproc.c, src/zsys.c
When trying to build on windows with the draft-api disabled, compilation fails for multiple reasons.
- some functions definitions in zsys.c have the CZMQ_EXPORT macro which conflicts in non-draft builds with the CZMQ_PRIVATE declaration of these functions in czmq_classes.h
- declaration of structs ztrie_t, zproc_t, zargs_t and ztimerset_t are disables in czmq_library.h for non-draft builds causing comilation errors in ztrie.c, zproc.c, zargs.c and ztimerset.c
For the second point I disabled the respective classes completely using the CZMQ_BUILD_DRAFT_API macro as they were not declared as private classes in non-draft builds.
=> Remove CZMQ_EXPORT for function definitions

builds/cmake/Modules/ClangFormat.cmake
Problem:
When building both libzmq and czmq with cmake, cmake fails because of the clang-format target being defined twice.  This PR renames the clang-format target to clang-format-czmq.  You can then make target with make clang-format-czmq.
(Also note that running clang-format target seems to break the code - it does not seem like this target is maintained or used for code checkins so maybe should remove)
=> clang-format custom target failes to build if building with libzmq

src/zuuid.c
Solution: use memcpy instead of strncat, which gets a warning with gcc
8 if the source string gets truncated. In this case it's intentional.
=> Problem: zuuid build fails with gcc 8

bindings/python_cffi/czmq_cffi/__init__.py, ci_build.sh, src/czmq_selftest.c, src/zsys.c
Solutions: see commits
See: https://github.com/zeromq/libzmq/pull/2971
=> Problems: atexit called after zmq static object destruction causes crash, out of date with zproject

api/zsys.api, include/zsys.h, src/zsys.c
This PR adds support for the new ZMQ_ZERO_COPY_RECV option of libzmq.
It is needed because zmq contexts are handled internally by czmq.
=> Support zmq zero copy option

src/zbeacon.c, src/zpoller.c
Solution: remove it. It is a backward-compat macro to use only with
the zmq_poll API, which used to take nanoseconds until libzmq 3.x
where it was changed to milliseconds.
In the zbeacon test it was used with zpoller_wait, which itself used it,
which means that when building with libzmq 2.x the timeout was twice
multiplied by 1000 and caused the test to hang.
Also remove it from the zmq_poller usage, which is new and has always
taken milliseconds.
Fixes #1825
=> Problem: tests hang due to ZMQ_POLL_MSEC used with zpoller and zmq_poller

.travis.yml
Solutions: allow the regen job to fail until https://github.com/zeromq/zproject/issues/947 is fixed, and install gsl/zproject packages
=> Problems: zproject regen generates broken JNI code and CI complains, packages not used

src/zloop.c, src/zproc.c
Solution: see commits.
I've added debugging code to `zloop_t`, because I have had troubles to find a way why was `zloop` interrupted in this case. It't not related to the problem, but helped me to find it.
=> Problem: zproc_set_stdin hangs the zproc instance

api/zconfig.api, include/zconfig.h, src/czmq_classes.h, src/zconfig.c
Solution: add `zconfig_dup` method, with the same semantics wrt NULL
handling as `zmsg_dup` has.
@bluca I did not mark it as draft, I'd say `dup` methods are pretty standard in CLASS/czmq, so there is nothing surprising on this method.
=> Problem: can't get a copy of zconfig

src/zdir.c
Solutions:
* check for NULL arguments before using them
* check for empty `path` when it is the full path (parent is `-`)
Notes about empty inputs to discuss (the more I look into this, the more I have no idea what we really want here)?
* empty path and empty parent implicitly means rootfs here; should it?.. actually empty parent seems not checked at all
* empty path and non-empty parent resolves into parent, this looks right
* empty parent and non-empty path resolves into a slash prefixed to path, so even a relative path becomes verbatim absolutized; is this expected?
Note: currently some tests actually pass the NULL parent value and so CI fails. Is this expected behavior (would enforcing the fix and updating tests break czmq consumer projects)? Does not seem to be well specified...
=> [WIP] zdir.c : zdir_new() : make sure all inputs are valid

appveyor.yml
Solution: reduce the number of randof tests by one order to save 3+ minutes (~40% of runtime)
=> Problem: appveyor jobs are very slow

src/zsys.c
Solution: use external ones
fixes: https://github.com/zeromq/czmq/issues/1899 https://github.com/zeromq/czmq/pull/1900
=> Problem: zsys_udp_new reference internal ZMQ macros

include/zproxy.h, src/zproxy.c
Solution: add a new DRAFT functionality to permit passing additional
parameters with the FRONTEND/BACKEND messages to the actor that will
be used to subscribe by SUB/XSUB sockets
Fixes #1905
=> Problem: zproxy API does not support subscribing to topics

include/czmq_prelude.h, src/zuuid.c
Solution: adjust the UUID defines so that libuuid is correctly used
on debian-kfreebsd, but not on other BSDs
=> Problem: debian-kfreebsd build broken

include/zproc.h, src/zproc.c, src/zsp.c
Solution: Rework zproc_wait to use timeout, use alarm () to exit from waitpid call
Create zproc_shutdown function that does the typical usecase TERM, wait, KILL
=> Problem: We can't wait for process with timeout

src/zargs.c
=> Problem: unused variable in zargs

src/zsys.c
Solution: replace win_assert() with zsys_socket_error().
=> Problem: win_assert() undefined, breaks Windows build.

src/zproc.c
Solution: When SIGTERM is received in app and zsys_interrupted
is set zproc never reads exit code of the process and it waits full
timeout. Solution is to ask for sub-process exit code and quit.
=> Problem: zproc creates zombie process on SIGTERM

src/zframe.c
While working on a new binding to CZMQ I noticed this mismatch in the comments in the zframe tests.
=> Problem: comment in zframe test is incorrect

src/zlistx.c
Solution: Fix the function and return the first item
For comparison, following are the implementations of zlistx_head and zlist_first (actually works) before the change, the difference should only be the cursor change, however the implementation is different:
```
void *
zlistx_head (zlistx_t *self)
{
assert (self);
return self->head? self->head->item: NULL;
}
void *
zlistx_first (zlistx_t *self)
{
assert (self);
self->cursor = self->head->next;
return self->cursor == self->head? NULL: self->cursor->item;
}
```
=> Problem: zlistx_head always return null

src/zhashx.c
In case zhashx_unpack get a malformed frame with few valid items,
the function will return a NULL however will leak all the already allocated items
Solution: free any items already allocated
=> Problem: zhashx_unpack is leaking memory in case of malformed frame

src/zhash.c, src/zhashx.c, src/zlistx.c
There is a crash in zhash_pack method when writting the 4 bytes corresponding to value length, to unaligned pointer address, this occur on Android armv7. I solve the problem using memcpy instead.
=> use memcpy on unaligned pointer to avoid crash on armv7 (BUS_ADRALN)

src/zsp.c
Problem: Warning on compilation by Windows Visual Studio 2015.
Solution: Use int64_t as zclock_mono().
=> Fixed the warning on Windows, start should use int64_t type.

bindings/python/test.py
Solution: 
* Zactor has no wait method but Zsock does, 
* fix callback arguments types were wrong
This is a fix however we are still doing it wrong I think. We're using c_void_p types for callback arguments but callbacks are always going back to python so we'd better user py_object types so arguments are PyObjects. We don't need casting then and can use any type. This needs fixing in zproject.
=> Problem: python ctypes test.py fails

.gitattributes, .gitignore, .travis.yml, Jenkinsfile, builds/abi-compliance-checker/ci_build.sh, project.xml, src/zhttp_client.c
Commented what was customized in the travis script, updated the solution with recent Jenkinsfile patterns improvements, etc.
Note that currently the travis script retains "trusty" as the build environment, like it was before. If this one works on CI, a next iteration can update the recipes to be even more compliant with current zproject.
PLEASE DO NOT MERGE before this ends up green in CI ;)
=> Regenerate CI build recipes with current zproject

src/zframe.c
Solution: If frommem is used the frame is being freed in the callback
=> Problem: zframe frommem function is accessing freed memory

src/zhttp_server.c
Solution: use older macro with libmicrohttp << 0.9.34
=> Problem: zhttp_server does not build on SUSE 12/42

api/zhttp_server.api, bindings/nodejs/README.md, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi/ZhttpServer.py, bindings/ruby/lib/czmq/ffi/zhttp_server.rb, src/zhttp_server.c
Solution: ifdef out the newer API, and warn users in the documentation
about possible side effects with the older version of the library.
It only affects SUSE 12/42 among the currently maintained Linux
distributions.
=> Problem: zhttp_server fails to build with libmicrohttpd << 0.9.34

src/zloop.c
Solution: 
* first delete timers to delete then break
* move rc==-1 check to beginning of loop to prevent the loop from not breaking
Here's a small test program which reproduces the problem:
```
#include "czmq.h"
static
int timer_end(zloop_t *loop, int timer_id, void *args) {
zloop_reader_end( loop, (zsock_t *)args);
return -1;
}
int socket_event(zloop_t *loop, zsock_t *handle, void *args)
{
zmsg_t *msg = zmsg_recv(handle);
zsys_notice( "Main sockect event: %s", zmsg_popstr( msg ));
zmsg_destroy(&msg);
return -1;
}
int main (void) {
zsys_init();
zloop_t *loop = zloop_new ();
assert (loop);
zloop_set_verbose (loop, true);
//add a socket
zsock_t *pub = zsock_new_pair("inproc://bla");
int rc = zloop_reader( loop, pub, socket_event, pub);
assert(rc == 0);
zloop_timer(loop, 1000, 1, timer_end, …
```
=> Problem: timers are called twice if they change the pollset

appveyor.yml
Solution: Use the correct dll name in the zip command
=> Problem: Appveyor does not include czmq's dll in artifacts

src/zbeacon.c
zbeacon: fix socket leak and minor check tweaks
=> zbeacon: fix socket leak

CMakeLists.txt, Findlibcurl.cmake, Findlibmicrohttpd.cmake, Findlibzmq.cmake, Findlz4.cmake, Findsystemd.cmake, README.md
=> Problem: Failed to build czmq on Windows via CMake

README.md, api/python_cffi.slurp, api/zlistx.api, bindings/delphi/CZMQ.pas, bindings/delphi/libczmq.pas, bindings/jni/src/main/java/org/zeromq/czmq/Zlistx.java, bindings/lua_ffi/czmq_ffi.lua, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi/Zlistx.py, bindings/python_cffi/czmq_cffi/cdefs.py, bindings/qml/src/QmlZlistx.cpp, bindings/qml/src/QmlZlistx.h, bindings/qt/src/qzlistx.cpp, bindings/qt/src/qzlistx.h, bindings/ruby/lib/czmq/ffi/zlistx.rb, include/zlistx.h, src/zlistx.c
Problem: typo in zlistx documentation
Solution: fix the typos
=> Fix "is any is" typos, should be "if any is"

packaging/redhat/czmq.spec, project.xml
Solution: Change license name formating to SPDX format in spec and project
metadata (so regenerating spec would keep the change).
=> Problem: openSUSE packaging requires SPDX formatted license

src/zhttp_response.c
Solution: Destroy the headers received from zhttp_client
=> Problem: zhttp_response_recv leaks memory when result is non-zero

include/czmq_prelude.h
Problem: MSVC now supports snprintf
Solution: Only replace snprintf with _snprint if the MSVC version is underneath 1500
=> Made snprintf available on MSVC versions over 1500

include/zframe.h, include/zmsg.h, src/zframe.c, src/zmsg.c
Solution: new zmsg_print_n and zframe_print_n functions
to print the specified amount of data without truncating.
```
```
git push -f
If you …
=> Problem: zframe_print output is truncated

src/zsys.c
Solution: Take care to initialize zsys before performing logging. This
is a lot more intuitive for new users because this issue can be quite
hard to figure out.
=> Problem: No logging if zsys is not initialized

.travis.yml
Solution: Generate a new one, encrypt it and replace the existing one
=> Problem: API key to deploy releases is no longer valid

src/zchunk.c
Solution: Ensure filehandle is non-null before calling zchunk_read().
=> Problem: zchunk_slurp() causes assert if file can't be opened

ci_deploy.sh
Solution: Re-generate the fix from zproject
=> Problem: ci_deploy check for empty BINDING_OPTS does the opposite

src/zbeacon.c
Problem: To set the interface used in zyre you must call zyre_set_interface, which ultimately calls zsys_set_interface(). The argument for this call is an interface NAME to use for resolution. 
On windows machines trying to determine an interface name is nearly a nightmare as its typically something like "Local Network Interface (1)" or something else long winded. Additionally this can change over time, and its hard for end users to deduce in the first place.
Solution: Allow the argument for zsys_set_interface to be an IP address OR interface name. This allows the end user to use something they can be more certain about (ip address) that is additionally guaranteed to not be randomly changed by the OS.
Ultimately you may wish to also update the docs for the other external functions to …
=> Allow zbeacon to resolve ip address to interface or interface name to interface

api/python_cffi.slurp, api/zsys.api, bindings/delphi/CZMQ.pas, bindings/delphi/libczmq.pas, bindings/jni/czmq-jni/src/main/c/org_zeromq_czmq_Zsys.c, bindings/jni/czmq-jni/src/main/java/org/zeromq/czmq/Zsys.java, bindings/lua_ffi/czmq_ffi.lua, bindings/nodejs/README.md, bindings/nodejs/binding.cc, bindings/nodejs/binding.h, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi/Zsys.py, bindings/python_cffi/czmq_cffi/cdefs.py, bindings/qml/src/QmlZsys.cpp, bindings/qml/src/QmlZsys.h, bindings/qt/src/qzsys.cpp, bindings/qt/src/qzsys.h, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/zsys.rb, include/zsys.h, src/czmq_classes.h, src/zbeacon.c, src/zsys.c
Problem: ipv4 multicast packet types when using zbeacon are not implemented - but some notes about it already exist in the code
Solution: Enable ipv4 multicast packet types when using zbeacon
Open Items:
I could not find the files used to gen czmq_selftest or czmq_private_selftest, thefore I could not update the auto code generator files for these. Do they exist?
I intentionally did not modify any behavior for ipv6 with this change zsys_udp_new() has the code to configure the socket differently for IPv6 but its not enabled.
I have not tested this code on any OS aside from windows. There I tested it going through atleast 1 router and verified TTL and addresses were set correctly with wire shark. Additionally I copied the existing beacon test and added the calls to configure it with …
=> Enable ipv4 multicast packet types when using zbeacon

include/czmq_prelude.h
```
Problem: The Android NDK API provides an implementation of ifaddrs.h after platform version 24.
Solution: Fixed ifdef code for android platforms to include a platform version check.
```
=> Android NDK platform 24 and above supports ifaddrs.h

.travis.yml, ci_deploy_obs.sh, packaging/obs/_service
Solution: now that tar_scm supports @PARENT_TAG@ as a revision to
automatically fetch the most recent tag on the default branch, use
it to simplify everything
https://github.com/openSUSE/obs-service-tar_scm/pull/359
Fixes https://github.com/zeromq/czmq/issues/2055
=> Problem: release script for OBS build fails often

builds/abi-compliance-checker/ci_build.sh
Solution: clone latest tag instead
=> Problem: removing latest_branch breaks ABI CI job

README.md, examples/security/strawhouse.c, include/zauth.h, src/zauth.c, src/zproxy.c
Solution: use more descriptive, accurate and welcoming terms like allowing
and blocking
=> Problem: documentation and code use unfriendly language

src/zsys.c
Solution: Set the s_initialized variable to false only at the end of the
function instead of the beginning.
Fixes #2084
=> Problem: zsys is re-initialized when logging an error in zsys_shutdown

doc/czmq.txt
```
Problem: czmq.txt  line#238-246 has typo 
Solution: should be replaced by
----
#if (defined (__UNIX__))
pid = getpid();
#elif (defined (__WINDOWS__))
pid = GetCurrentProcessId();
#else
pid = 0;
#endif
----
```
=> fix the example code in czmq.txt

src/zproc.c
=> Problem: "quit" variable in zproc_wait() can overflow

src/zchunk.c, src/zsys.c
Solution: use the chunk's actual size (self->size) instead of max_size.
Also added the cleanup of log_sender in zsys which left a dangling socket during tests.
=> Problem: zchunck pack() is creating frames based on the maximum instead of actual size

api/python_cffi.slurp, api/zsys.api, bindings/delphi/CZMQ.pas, bindings/delphi/libczmq.pas, bindings/jni/czmq-jni/src/main/c/org_zeromq_czmq_Zsys.c, bindings/jni/czmq-jni/src/main/java/org/zeromq/czmq/Zsys.java, bindings/lua_ffi/czmq_ffi.lua, bindings/nodejs/README.md, bindings/nodejs/binding.cc, bindings/nodejs/binding.h, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi/Zsys.py, bindings/python_cffi/czmq_cffi/cdefs.py, bindings/qml/src/QmlZsys.cpp, bindings/qml/src/QmlZsys.h, bindings/qt/src/qzsys.cpp, bindings/qt/src/qzsys.h, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/zsys.rb, include/zsys.h, src/czmq_classes.h, src/zsys.c
Problem: it's inconvenient to do ipv6 stuff if it isn't available
Solution: add a zsys_ipv6_available method to test whether ipv6 is available like done in libzmq
This method is ported from libzmq and it has served me well. Might as well add it to czmq.
=> Check for ipv6 availability

src/zgossip.c
Solution : in clients, monitor connections with gossip servers to reinitiate tuples exchanges on server reconnection
=> Problem: if gossip server disconnects and reconnects, persisting gossip clients do not exchange tuples anymore when server reconnects

src/zarmour.c
Solution: edit test to properly check encoding/decoding of empty strings
NB: The core problem may be in libzmq with an unwanted API change.
=> Problem: zarmour tests are broken for internal Z85 encoding

include/zcertstore.h, src/zcertstore.c
```
Problem: 
We encountered 2 different issues listed below w.r.t CURVE authentication which uses zcertstore internally to store the client keys.
If there are multiple client certs with same timestamp or one of the cert has timestamp
a. On client connection request certstore gets refreshed
b. after that a new client cert is copied or valid cert is overwritten as the previous cert was invalid or corrupted, the certstore does not get refreshed and there after that connection will never be allowed as there is not change w.r.t timestamp, count and current size of the cert dir
If an application wants to load its custom disk loader (which loads …
```
=> zcertstore has no API to get the disk state from a custom loader #2113

src/zbeacon.c
Solution: removes usage when building for QNX. Closes #2118
=> Problem: QNX does not support AI_V4MAPPED

acinclude.m4, src/CMakeLists-local.txt, src/zbeacon.c
Solution: Instead of checking for platforms that don't have AI_V4MAPPED
defined - which may to change in the future - use autotools or cmake
to check for the symbol.
If found they'll declare the define HAVE_DECL_AI_V4MAPPED with value 1
otherwise 0.
=> Problem: Check for symbol AI_V4MAPPED based on incomplete platform list

README.md, README.txt
Problem: it's unclear how to unlock the draft APIs
Solution: add a note in the documentation
=> add doc remark about unlocking draft APIs

src/zosc.c
Problem: Sending a single char through zosc was one byte off
Solution: remove the offending byte
=> zosc: sending a char was one byte too big

api/python_cffi.slurp, api/zosc.api, bindings/jni/czmq-jni/src/main/java/org/zeromq/czmq/Zosc.java, bindings/lua_ffi/czmq_ffi.lua, bindings/nodejs/README.md, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi/Zosc.py, bindings/python_cffi/czmq_cffi/cdefs.py, bindings/qml/src/QmlZosc.cpp, bindings/qml/src/QmlZosc.h, bindings/qt/src/qzosc.cpp, bindings/qt/src/qzosc.h, bindings/ruby/lib/czmq/ffi/zosc.rb, builds/android/android_build_helper.sh, include/zosc.h, src/zosc.c
Problem: zosc_print wasn't implemented, zproject is out of date.
Solution: implement zosc_print similar to liblo, regenerate from zproject
=> Implement zosc_print similar to liblo oscdump

src/zosc.c
Problem MSVC C compiler complains about array bounds overflow c2117
Solution: workaround including a terminating NULL
=> Windows c compiler is not happy about zosc 

api/python_cffi.slurp, api/zosc.api, bindings/jni/czmq-jni/src/main/c/org_zeromq_czmq_Zosc.c, bindings/jni/czmq-jni/src/main/java/org/zeromq/czmq/Zosc.java, bindings/lua_ffi/czmq_ffi.lua, bindings/nodejs/README.md, bindings/nodejs/binding.cc, bindings/nodejs/binding.h, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi/Zosc.py, bindings/python_cffi/czmq_cffi/cdefs.py, bindings/qml/src/QmlZosc.cpp, bindings/qml/src/QmlZosc.h, bindings/qt/src/qzosc.cpp, bindings/qt/src/qzosc.h, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/zosc.rb, include/zosc.h, src/zosc.c
Problem: It's difficult to get values from zosc message dynamically.
Solution: Implement an iterator and pop_<type> methods.
Also fixes a problem with printing floats and doubles!
Regenerate from zproject.
=> Problem: getting values from zosc message without knowing the format before hand

src/zosc.c
Problem: Zosc is being too verbose
Solution: remove unnecessary print statements or condition it
=> Zosc: remove unnecessary print statements

src/zhashx.c
The zhashx_dup() function does not duplicate the source hash perfectly.
It does not duplicate the source hash's hasher function, as the well as
the key destructor, duplicator, or comparator.  This minimally can lead
to unexpected behavior of the duplicate zhashx.  At worst it can cause
assert/segfault/memory corruption as zhashx defaults access/free unintended
memory.
Solution: Copy the source hasher, key destructor, key duplicator,
and key comparator over to the newly duplicated zhashx.
Fixes #2144
=> Problem: [zhashx] zhashx_dup() does not copy callbacks

src/zsock.c, src/zsys.c
Problem: zsys_sockname is missing DGRAM sockets
Solution: add DGRAM sockets to zsys_sockname
Also add it to the test.
=> zsys_sockname is missing DGRAM sockets

README.md
Add link to iOS static compilation scripts. @sappo mentioned doing so in https://github.com/zeromq/czmq/issues/2148. 
[CONTRIBUTING.md](https://github.com/zeromq/czmq/blob/master/CONTRIBUTING.md)
=> Update README.md with iOS static compilation link. 

src/zosc.c
Problem: When appending data the length of the new format string is calculated wrong when it is 4 byte aligned
Solution: include a byte for the terminating null byte when calculating the new string length
=> Appending data calculates the new osc format string incorrect

src/zosc.c
Problem: segfault when appending to an empty message
Solution: initialise the format string properly
=> initialise format string on the heap

src/zsock.c, src/zsys.c
This patch addresses three problems related to ZSYS_THREAD_NAME_PREFIX / ZSYS_THREAD_NAME_PREFIX_STR:
1. Setting ZSYS_THREAD_NAME_PREFIX_STR is ignored (it reads ZSYS_THREAD_NAME_PREFIX when set)
2. ZSYS_THREAD_NAME_PREFIX is ignored (it uses the default for ZSYS_THREAD_NAME_PREFIX_STR instead)
3. Programs on MacOS immediately crash on startup (due to a strcpy(s,s), which is illegal)
I changed the minimal amount necessary to fix the problems, but I think this interface is confusing for users and does not really reflect the underlying libzmq implementation. I would much prefer a single environment variable ZSYS_THREAD_NAME_PREFIX where the implementation in czmq figures out which libzmq API to call, based on whether  the value specified is an integer or some other string.
=> Fix problems related to ZSYS_THREAD_NAME_PREFIX/ZSYS_THREAD_NAME_PREFIX_STR

src/zhashx.c
When rehashing in s_item_lookup(), the chain limit was not increased.
Therefore, the chain limit stayed at its default value of 1.  By staying
at the default value of 1, a single hash collision could increase the
limit of the hash.  This increase could be well beyond what would be
reasonable.
Solution: Increase the chain limit by the growth factor after a rehash.
Fixes #2173
=> Problem: [zhashx] rehash does not increase chain limit

src/zuuid.c
**Problem**: Compilation on OpenBSD is broken as the "defined" checks on OpenBSD short-circuit at HAVE_UUID and does not reach __UTYPE_OPENBSD, resulting in the error:
```
src/zuuid.c:70:31: error: operand of type 'uuid_t' (aka 'struct uuid') where arithmetic or pointer type is required
zuuid_set (self, (byte *) uuid);
```
**Solution**: Reorder the HAVE_UUID defined checks so that the BSD-specific UTYPEs can be found first. Tested on OpenBSD 6.9.
=> Change zuuid HAVE_UUID defined check order to fix broken compilation on OpenBSD

src/zosc.c
Problem: zosc is leaking its address and format string
Solution: keep format on the stack and move address to the chunk like it should
=> fix zosc leak by moving address to the chunk

src/zosc.c
Problem: As mentioned in #2163 czmq doesn't want to build on BSD and mingw. The provided patch however created new issues. 
Solution: add correct precompiler statements for mentioned platforms
This supersedes #2163 so it can be closed @vchuravy @giordano
=> Fix for compilation on BSD and mingw

src/zosc.c
Problem: OSX is failing to build because of missing endian.h
Solution: add correct include for OSX specifically
additional problem: large zosc message are flooding the logs
solution: only warn for large messages once.
=> OSX is failing on missing endian.h, prevent flooding logs

bindings/jni/gradle/wrapper/gradle-wrapper.properties
Solution: Manually update the gradle version from gradle-wrapper.properties
=> Problem: Gradle version of JNI bindings is not updated automatically

bindings/jni/ci_build.sh, builds/cmake/ci_build.sh, builds/rpi/build.sh, ci_build.sh, project.xml
Problem: Curl needs a configure option for encryption
Solution: add config option to zproject config
=> OSX CI build fails due to upstream curl change

src/zosc.c
Problem: appending to an empty zosc message results in invalid message.
Solution: only copy old data if there was any
=> Fix for appending to an empty zosc message

src/zosc.c
Solution: add proper IOS condition for includes at head of the file
=> Problem: zosc.c does not use proper endian management macros on ios

src/zframe.c, src/zmsg.c
Solution:
- in zframe, use freen instead of zframe_destroy when frame init fails (heap exhaustion which may be due to message corruption) to avoid a bad memory access on the still unallocated self->zmsg
- in zmsg, break and return NULL instead of asserting after trying to initiate the zmsg from the decoded frame if the frame is NULL
=> problem: corrupted zframes called in zmsg_decode create a crash instead of returning NULL

src/zdir.c
Problem: zdir_flatten pushes subdirs at the end causing problems with patches computation in zdir_diff
For example, when a file is added in the root directory and alphabetically placed between two subdirs, zdir_diff generates false create/delete patches for all the files in the subdirs.
Solution: sort the whole flat list generated by zdir_flatten after all recursions are over.
=> Problem: zdir_flatten pushes subdirs at the end causing problems with patches computation in zdir_diff

src/zframe.c
reduce runtime cost when checking if the frame is binary or not,
in zframe_print_n()  & zframe_fprint()
=> zframe.c/print: reduce runtime cost

.circleci/config.yml, builds/stable_zmq/ci_build.sh, doc/czmq.txt
Following https://github.com/zeromq/czmq/pull/2235, I checked deeper and found some more such references:
```
prompt> cd czmq
prompt> find . -type f | grep -v '/.git/' | xargs grep 'git://github.com'
./.circleci/config.yml:            git clone --depth 1 --quiet git://github.com/sappo/czmq.git "$Env:CZMQ_DIR"
./builds/stable_zmq/ci_build.sh:    git clone --quiet --depth 1 -b stable git://github.com/jedisct1/libsodium.git
./doc/czmq.txt:    git clone git://github.com/zeromq/czmq.git
prompt>
```
Solution: Fix invalid `git://github.com` URLs.
Note: Similar task in progress in ZYRE.
```
``` …
=> Problem: More invalid links to git://github.com

include/zproxy.h, src/zproxy.c
In order to clean out broken TCP connections with the proxy.
Example usage:
```c
proxy = zactor_new (zproxy, NULL); assert (proxy);
// Set the frontend (incoming messages)
char endpoint[64] =  { 0, };
sprintf(endpoint, "tcp://*:%d", in_port);
zstr_sendx (proxy, "FRONTEND", "XSUB", endpoint,
"HEARTBEAT_IVL", "300000", "HEARTBEAT_TIMEOUT", "30000",
"HEARTBEAT_TTL", "0", NULL);
zsock_wait (proxy);
```
Fixes #2244
=> zproxy: Add heartbeat command

AUTHORS, api/python_cffi.slurp, api/ziflist.api, bindings/delphi/CZMQ.pas, bindings/delphi/libczmq.pas, bindings/jni/czmq-jni/src/main/c/org_zeromq_czmq_Ziflist.c, bindings/jni/czmq-jni/src/main/java/org/zeromq/czmq/Ziflist.java, bindings/lua_ffi/czmq_ffi.lua, bindings/nodejs/README.md, bindings/nodejs/binding.cc, bindings/nodejs/binding.h, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi/Ziflist.py, bindings/python_cffi/czmq_cffi/cdefs.py, bindings/qml/src/QmlZiflist.cpp, bindings/qml/src/QmlZiflist.h, bindings/qt/src/qziflist.cpp, bindings/qt/src/qziflist.h, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/ziflist.rb, include/czmq_prelude.h, include/ziflist.h, src/czmq_classes.h, src/ziflist.c
Problem: The ziflist class doesn't expose macaddresses of interfaces
Solution: add the macaddress to the ziflist items
=> Feature: adding macaddress to ziflist items

api/python_cffi.slurp, api/zdir.api, bindings/delphi/CZMQ.pas, bindings/delphi/libczmq.pas, bindings/jni/czmq-jni/src/main/c/org_zeromq_czmq_Zdir.c, bindings/jni/czmq-jni/src/main/java/org/zeromq/czmq/Zdir.java, bindings/lua_ffi/czmq_ffi.lua, bindings/nodejs/README.md, bindings/nodejs/binding.cc, bindings/nodejs/binding.h, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi/Zdir.py, bindings/python_cffi/czmq_cffi/cdefs.py, bindings/qml/src/QmlZdir.cpp, bindings/qml/src/QmlZdir.h, bindings/qt/src/qzdir.cpp, bindings/qt/src/qzdir.h, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/zdir.rb, include/zdir.h, src/zdir.c
Solution: zdir_list_paths return a char* list of all the files and subdirectories of zdir
=> Problem: zdir_list omits empty subdirectories

src/zhash.c
Solution: add an assert after call to strdup during item insertion
```
```
git push -f
If you are a new contributor please have a look at our …
=> Problem: strdup can fail creating a new item with a bad key

README.md, api/python_cffi.slurp, api/zlist.api, api/zlistx.api, bindings/delphi/CZMQ.pas, bindings/delphi/libczmq.pas, bindings/jni/czmq-jni/src/main/java/org/zeromq/czmq/Zlist.java, bindings/jni/czmq-jni/src/main/java/org/zeromq/czmq/Zlistx.java, bindings/lua_ffi/czmq_ffi.lua, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi/Zlist.py, bindings/python_cffi/czmq_cffi/Zlistx.py, bindings/python_cffi/czmq_cffi/cdefs.py, bindings/qml/src/QmlZlist.cpp, bindings/qml/src/QmlZlist.h, bindings/qml/src/QmlZlistx.cpp, bindings/qml/src/QmlZlistx.h, bindings/qt/src/qzlist.cpp, bindings/qt/src/qzlist.h, bindings/qt/src/qzlistx.cpp, bindings/qt/src/qzlistx.h, bindings/ruby/lib/czmq/ffi/zlist.rb, bindings/ruby/lib/czmq/ffi/zlistx.rb, include/zlist.h, include/zlistx.h, src/zlistx.c
I noticed a few comments in the headers for zlist/zlistx that mention errors are returned on out of memory conditions.  I believe those errors are no longer possible, as czmq is built with asserts to bail if any internal memory allocation fails.  Apologies if I'm wrong about this.
For `zlist`, I just changed the example error of "out of memory" to "invalid input", which is a real possible error.  For `zlistx`, I just removed the offending text.
=> Update zlist/zlistx header comments to indicate memory exhaustion not possible error

src/zloop.c, src/zsock.c
If SIGINT signal arrives while poll is blocking, regardless of attached signal handler it will cause the poll to return with errno EINTR. Currently, this causes zloop to return from the event loop. For nonstop mode to work as intended, we have to ignore EINTR in this case.
Added test cases that verify the functionality when catching an actual SIGINT signal with and without nonstop mode. Tested in Linux and Windows.
Fixes #2284
=> zloop: ignore EINTR from poll if nonstop is enabled

api/python_cffi.slurp, api/zproc.api, bindings/delphi/CZMQ.pas, bindings/jni/czmq-jni/src/main/java/org/zeromq/czmq/Zproc.java, bindings/lua_ffi/czmq_ffi.lua, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi/Zproc.py, bindings/python_cffi/czmq_cffi/cdefs.py, bindings/qml/src/QmlZproc.cpp, bindings/qml/src/QmlZproc.h, bindings/qt/src/qzproc.cpp, bindings/qt/src/qzproc.h, bindings/ruby/lib/czmq/ffi/zproc.rb
Solution: Run GSL on the project.xml
These changes are potentially superfluous, but since I am running `tstgenbld.sh`, I might as well update most projects to the latest versions while learning zproject.
There were two misspellings that was fixed on czmq that came from zproject generation (and thus regenerating them would bring back the misspellings) via https://github.com/zeromq/czmq/pull/2273. I fixed the one related to the API and I ommitted the one that came from zproject itself, as I will make a pull request to zproject to fix it.
=> Problem: Out of date zproject

src/zloop.c
Problem: Issue 2278; loop->terminated == true when restarting a loop allowing timer callbacks to update loop->timers in place.
Solution: Set loop->terminated = false at beginning of zloop_start. Add test to both demonstrate the issue and test the fix.
=> Fixed issue 2278, loop->terminated == true when restarting a loop

src/zloop.c
If no sockets or actors are used in zloop, `zsys_init()` does not get run and zsys interrupt handler does not get initialized. This means that interrupts will not work correctly in zloop if, for example, only timers are used. `zsys_init()` is safe to call multiple times, so we ensure that it's called when new zloop instance is created.
=> zloop: ensure zsys_init() when creating zloop

api/python_cffi.slurp, api/zosc.api, bindings/jni/czmq-jni/src/main/c/org_zeromq_czmq_Zosc.c, bindings/jni/czmq-jni/src/main/java/org/zeromq/czmq/Zosc.java, bindings/lua_ffi/czmq_ffi.lua, bindings/nodejs/README.md, bindings/nodejs/binding.cc, bindings/nodejs/binding.h, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi/Zosc.py, bindings/python_cffi/czmq_cffi/cdefs.py, bindings/qml/src/QmlZosc.cpp, bindings/qml/src/QmlZosc.h, bindings/qt/src/qzosc.cpp, bindings/qt/src/qzosc.h, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/zosc.rb, include/zosc.h, src/zosc.c
Problem: it's not easy to create a message simply by describing it like how a message can be printed as a string
Solution: Add zosc_fromstring method enabling the creation of message from a string
Also added test code.
A message can be constructed as follows:
```c
zosc_t* msg = zosc_fromstring("/stringmsg ihfdscF 32 64 1.100000 3.140000 hello q");
```
=> Create an OSC message from a string

api/python_cffi.slurp, api/zhttp_request.api, bindings/jni/czmq-jni/src/main/c/org_zeromq_czmq_ZhttpRequest.c, bindings/jni/czmq-jni/src/main/java/org/zeromq/czmq/ZhttpRequest.java, bindings/lua_ffi/czmq_ffi.lua, bindings/nodejs/README.md, bindings/nodejs/binding.cc, bindings/nodejs/binding.h, bindings/python/czmq/_czmq_ctypes.py, bindings/python_cffi/czmq_cffi/ZhttpRequest.py, bindings/python_cffi/czmq_cffi/cdefs.py, bindings/qml/src/QmlZhttpRequest.cpp, bindings/qml/src/QmlZhttpRequest.h, bindings/qt/src/qzhttprequest.cpp, bindings/qt/src/qzhttprequest.h, bindings/ruby/lib/czmq/ffi.rb, bindings/ruby/lib/czmq/ffi/zhttp_request.rb, include/zhttp_request.h, src/zhttp_client.c, src/zhttp_request.c
Solution: Add functions to zhttp_request to set username and password, and send these to the client.
=> Problem: zhttp_client does not support authentication

.github/workflows/CI.yaml, configure.ac
=> Upgrade generated CI to Ubuntu 24.04 (regen from ZProject).

include/czmq_prelude.h
Soltion: only add bool if the standard is lower than C23
=> Fix: MSVC C23 bool typedef causes an error

bindings/jni/ci_build.sh, builds/android/build.sh, builds/cmake/ci_build.sh, builds/rpi/build.sh, ci_build.sh, project.xml
See issue #2323 for traces and details.
Solution: Use any of its mirrors with the help of `ftpmirror.ftp.org`.
1st commit applied in `project.xml`.
2nd commit is the result of regenerate.
=> Problem: Android CI build fails due to LIBMICROHTTPD download failure
