zeromq/czmq

doc/zconfig.doc
doc/zconfig.txt
doc/zfile.doc
doc/zfile.txt
include/zconfig.h
include/zfile.h
src/zconfig.c
src/zfile.c
src/zuuid.c

Minor improvements

---

include/czmq_prelude.h

Solution: define these if missing.

Problem: PRId8/16/32 and PRIuXX not defined on Windows

---

README.md
README.txt

Solution: add link to Go bindings

Problem: README does not include Go bindings

---

builds/qt-android/build.sh

Solution: copy changes from latest zproject

Problem: qt-android build script out of date

---

include/czmq_prelude.h
src/Makemodule.am
src/zsys.c

Solution: Use android builtin logging mechanism on android

Problem: Logging to stdout isn't visible on android

---

include/zsys.h
src/zsys.c

Solution: return NULL in this case
Fixes #907

Problem: zsys_hostname crashed if gethostbyname failed

---

src/zsys.c

Solution: Only try to set socket options if the handle isn't NULL.
This lets applications gracefully handle the inability to create more
sockets in some way other than crashing the application with an
assertion failure.

Problem: zsys_socket SIGABRTs when zmq_socket fails.

---

CMakeLists.txt
doc/Makefile.am
doc/zloop.doc
doc/zloop.txt
doc/zsys.doc
doc/zsys.txt
model/build-autoconf.gsl
src/Makemodule.am
src/zsys.c

This rolls back a commit of generated files that resulted in a break. The first attempt to move one of the manually-edited generated file changes into the template resulted in a a subsequent break. A subsequent attempt to roll back was in error. This pull request reverts the three commits that are in error.
**Please do not merge until it passes all Travis builds.** Once this is good I will add my changes to correct the several areas where the templates and generated files are out of sync.

Problem: broken build.

---

configure.ac
src/Makemodule.am

Solution: Regenerate using updated zproject
Fixes #927

Problem:  configuration was broken.

---

api/zhash.xml
api/zmsg.xml
bindings/python/czmq.py
bindings/python/test.py
bindings/ruby/lib/czmq/ffi/zhash.rb
bindings/ruby/lib/czmq/ffi/zmsg.rb

Solution: Add freshness specifier where appropriate, regenerate

Problem: Missing fresh state on API definitions

---

api/zframe.xml
api/zhash.xml
api/zloop.xml
api/zsock.xml
bindings/python/czmq.py
bindings/qml/src/QmlZframe.cpp
bindings/qml/src/QmlZframe.h
bindings/ruby/lib/czmq/ffi/zframe.rb
builds/msvc/vs2008/czmq/czmq.vcproj
builds/msvc/vs2010/czmq/czmq.vcxproj
builds/msvc/vs2010/czmq/czmq.vcxproj.filters
builds/msvc/vs2012/czmq/czmq.vcxproj
builds/msvc/vs2012/czmq/czmq.vcxproj.filters
builds/msvc/vs2013/czmq/czmq.vcxproj
builds/msvc/vs2013/czmq/czmq.vcxproj.filters
include/zframe.h
src/Makemodule.am

Solution: Regenerate using latest zproject, revert documentation changes
in model files

Problem: Inadvertent documentation changes, and zproject regression

---

api/zhash.xml
api/zlist.xml
api/zloop.xml
api/zsock.xml

Solution: Use exclude method attribute instead of has_print class attribute

Problem: Convention in zproject for excluding implicit methods changed

---

api/zframe.xml

Solution: clarify when data is allocated and copied.
Somewhat stepped on toes of previous commit...

Problem: zframe_new docs aren't helpful

---

src/zsys.c

Solution: do not resolve host if it's null

Problem: segfault in zsys.c:971

---

CMakeLists.txt
api/zmsg.xml
api/zsock.xml
bindings/python/czmq.py
bindings/qml/src/QmlZframe.cpp
bindings/qml/src/QmlZframe.h
bindings/qml/src/QmlZmsg.cpp
bindings/qml/src/QmlZmsg.h
bindings/ruby/lib/czmq/ffi/zframe.rb
bindings/ruby/lib/czmq/ffi/zmsg.rb
bindings/ruby/lib/czmq/ffi/zsock.rb
include/czmq_library.h
include/zframe.h
src/czmq_classes.h

caused object leaks in bindings.

Fixes for definition issues with zsock & zmsg

---

bindings/python/czmq.py
bindings/python/test.py
src/Makemodule-local.am

Turned up a load of the issues which I've been commiting to zproject, and shows how to use the bindings too.

Implement self-tests for all bound classes for Python bindings

---

builds/msvc/properties/ReleaseDEXE.props

See https://github.com/zeromq/czmq/issues/954

Problem: wrong default VC rt lib for release dynamic exe.

---

api/zdir.xml
bindings/python/czmq.py
bindings/qml/src/QmlZdir.cpp
bindings/qml/src/QmlZdir.h
bindings/ruby/lib/czmq/ffi.rb
bindings/ruby/lib/czmq/ffi/zdir.rb
include/zdir.h
src/zdir.c

Solution: zdir_watch actor
Starts to fix #826

Problem: Unable to easily watch a directory for changes.

---

bindings/python/test.py

Solution: Translate zdir test into Python

Problem: Python bindings tests didn't include zdir_watch

---

include/zgossip.h
src/zgossip_engine.inc
src/zgossip_msg.c
src/zgossip_msg.h

Nothing hand-written - it's all regenerated via zproto.
Fixes  #953

Zgossip hang fix

---

doc/zsock.doc
doc/zsock.txt
include/zsock.h
src/zproxy.c

Problem: man page for zsock is incorrect re @ and >

---

include/zuuid.h
src/zuuid.c

Broke/fixed zuuid_formatted_str

Code cleanups

---

api/ziflist.xml
bindings/python/czmq.py
bindings/qml/src/QmlZiflist.cpp
bindings/qml/src/QmlZiflist.h
bindings/ruby/lib/czmq/ffi.rb
bindings/ruby/lib/czmq/ffi/ziflist.rb
include/ziflist.h
src/ziflist.c

Solution: Implement ziflist_print

Problem: No print method for ziflist.

---

bindings/python/test.py
src/zlist.c

fixed error: variable 'swapped' set but not used

Problem:variable 'swapped' set but not used

---

doc/zlist.doc
doc/zlist.txt
doc/zrex.doc
doc/zrex.txt

Solution: add it, so man page shows selftest correctly.

Problem: zrex selftest tag is missing

---

foreign/sha1/sha1.c
foreign/slre/slre.c
foreign/slre/slre.h
include/zgossip.h
src/zarmour.c
src/zconfig.c
src/zdir.c
src/zfile.c
src/zgossip_engine.inc
src/zgossip_msg.c
src/zhash.c
src/zhashx.c
src/zlist.c
src/zlistx.c
src/zloop.c
src/zrex.c
src/zsock.c
src/zstr.c
src/zsys.c

See: https://github.com/zeromq/czmq/issues/978

Problem: integer narrowing and sign mismatch issues.

---

api/zsock.xml
bindings/python/czmq.py
bindings/qml/src/QmlZsock.cpp
bindings/qml/src/QmlZsock.h
bindings/ruby/lib/czmq/ffi/zsock.rb
include/zframe.h
include/zsock.h
src/zframe.c
src/zgossip_engine.inc
src/zgossip_msg.c
src/zgossip_msg.h
src/zpoller.c
src/zrex.c
src/zsock.c

Solution: caused by error in zproto_codec_c; fixed in zproto and
regenerated here.
Fixes #1000

Problem: compiler warning on zgossip_msg.c:442

---

include/zchunk.h

Solution: added zchunk_extend to zchunk.h

Problem: zchunk_extend missing from header

---

src/zsys.c

see also: http://lists.zeromq.org/pipermail/zeromq-dev/2015-May/028953.html

zsys/logging: use zsock API for logging, zsock_attach syntax for logging endpoints

---

README.txt
api/zsock.xml
bindings/python/czmq.py
bindings/qml/src/QmlZsock.cpp
bindings/qml/src/QmlZsock.h
bindings/ruby/lib/czmq/ffi/zsock.rb
doc/asciidoc.conf
doc/zchunk.doc
doc/zchunk.txt
doc/zframe.doc
doc/zframe.txt
doc/zlistx.doc
doc/zlistx.txt
doc/zsock.doc
doc/zsock.txt
include/zsock.h

Problem: documentation is out of date

---

doc/zgossip.doc
doc/zgossip.txt
doc/zgossip_msg.txt
include/zgossip.h
src/zgossip.xml
src/zgossip_engine.inc
src/zgossip_msg.c

Solution: remove it (it's a private class).

Problem: zgossip_msg.txt should not be in doc directory

---

include/zmsg.h
src/zmsg.c

implement zmsg_sendm in zmsg files. it almost copy from zmsg_send,but keep ZFRAME_MORE flag  during sending.
sometimes it is useful.

implement zmsg_sendm

---

Makefile.am
NEWS
bindings/ruby/lib/czmq/ffi/version.rb
include/czmq_library.h
project.xml
version.sh

Some key files were missing from the tarballs.

Release 3.0.2

---

bindings/ruby/lib/czmq/ffi/version.rb
include/czmq_library.h
project.xml
version.sh

Solution: change in project.xml and rebuild.

Problem: need to bump version number after release

---

CMakeLists.txt
autogen.sh
configure.ac

Solution: Run ./generate.sh with latest zproject.

Problem: Build system is out of date.

---

.travis.yml

Add CI build with zeromq4-1. Fixes #1055

---

include/zframe.h
include/zsock.h
src/zframe.c
src/zsock.c

* Add the socket type to zsock
* Retrieving and setting the routing id on zframe

Add client server to czmq

---

bindings/ruby/lib/czmq/ffi/zactor.rb
bindings/ruby/lib/czmq/ffi/zdir.rb
bindings/ruby/lib/czmq/ffi/zdir_patch.rb
bindings/ruby/lib/czmq/ffi/zframe.rb
bindings/ruby/lib/czmq/ffi/zmsg.rb
bindings/ruby/lib/czmq/ffi/zsock.rb

Solution: Fix in zproject and regenerate here.
See: https://github.com/zeromq/zproject/pull/211
Relates to: https://github.com/zeromq/czmq/issues/1062

Problem: Ruby bindings clash with self and alias keywords.

---

include/zlistx.h
src/zlistx.c

Solution: Add method to get both head and tail
I also did some minor code clean-up and removed unused variable tail.

Problem: Cannot obtain head and tail of zlistx

---

src/ztrie.c

Solution: Ignore trailing delimiter and fail on empty tokens

Problem: ztrie crashed on invalid routes

---

CMakeLists.txt
Makefile.am
bindings/python/czmq.py
bindings/qml/src/QmlZmsg.cpp
bindings/qml/src/QmlZmsg.h
bindings/qml/src/QmlZsock.cpp
bindings/qml/src/QmlZsock.h
bindings/ruby/lib/czmq/ffi/zmsg.rb
bindings/ruby/lib/czmq/ffi/zsock.rb
builds/qt-android/android_build_helper.sh
builds/qt-android/build.sh
configure.ac
include/zmsg.h
include/zsock.h
project.xml

Solution: Use zproject's new optional dependency instead

Problem: libuuid is hardcoded as optional dependency

---

include/zproxy.h
src/zproxy.c

Added ability to configure CURVE and PLAIN security options through new zproxy API commands for the frontend and backend sockets of the proxy.

Added authentication commands to zproxy actor.

---

src/zproxy.c

Code clean up to better match CLASS style guide.

Updated code to better meet style guide.

---

src/ztrie.c

Solution: use own implementation of strndup which works cross platform.
@ritchiecarroll could you please verify if this works for windows as well. Thanks!

Problem: strndup is not cross platform

---

include/zgossip.h
src/license.xml
src/zarmour.xml
src/zclass_example.xml
src/zgossip.xml
src/zgossip_engine.inc
src/zgossip_msg.c
src/zgossip_msg.h
src/zgossip_msg.xml

Solution: Kill it and regenerate the zproto code with license.xml
fixes #1090

Problem: src/license.xml is redundant/old

---

src/zproxy.c

Validated that each zauth test step was replicated in zproxy auth tests to keep them in harmony. Also changed test connections from zsock_attach to zsock_connect for simplicity.

Updated zproxy actor authentication test steps to match each step found in zauth actor test

---

src/zmsg.c

retrying until complete message is send/received.
Fix the frame leak if a message send fails, do not remove a frame from the
message list until the send has completed successfully.

If interrupted in a middle of a multipart send or receive sequence, keep

---

AUTHORS
src/zproxy.c

Updated test code flow to improve Travis CI build results.

Updated zproxy tests for authentication to correct CI errors

---

src/zframe.c

Solution: change it to malloc.

Problem: zframe_strhex is needlessly using zmalloc

---

CMakeLists.txt
Makefile.am
builds/qt-android/build.sh
builds/qt-android/ci_build.sh
configure.ac
project.xml

Solution: change the dependency name and regenerate zproject files.

Problem: zproject changed the known dependency name for zmq to libzmq

---

README.md
include/zchunk.h
src/zchunk.c

Solution: fixed the typos
@jemc you're too slow :P

Problem: zchunk comments contain typos

---

src/zdir.c

Problem: zdir.c uses illegal for declaration

---

CMakeLists.txt
FindUuid.cmake
FindZeroMQ.cmake
bindings/qt/src/qzactor.h
bindings/qt/src/qzdir.h
bindings/qt/src/qzdirpatch.h
bindings/qt/src/qzfile.h
bindings/qt/src/qzframe.h
bindings/qt/src/qzhash.h
bindings/qt/src/qzhashx.h
bindings/qt/src/qziflist.h
bindings/qt/src/qzlist.h
bindings/qt/src/qzloop.h
bindings/qt/src/qzmsg.h
bindings/qt/src/qzpoller.h
bindings/qt/src/qzsock.h
bindings/qt/src/qzstr.h
bindings/qt/src/qztrie.h
bindings/qt/src/qzuuid.h

Solution: regenerate from zproject to fix CMake files

Problem: cmake build broken due to wrong var name

---

bindings/python/czmq.py

Solution: Regenerate from zproject

Problem: Python bindings generation issue cause error

---

api/zactor.xml
api/zdir.xml
api/zdir_patch.xml
api/zfile.xml
api/ziflist.xml

Problem: self test methods missing in some APIs

---

src/zpoller.c

Solution: make the zpoller work with the new zmq_poller.
@taotetek you can use zpoller with server and client now...

problem: polling on multiple thread safe sockets with zpoller is not possible

---

src/zpoller.c

Problem: zpoller test are failing

---

api/zsock.xml

Problem: Wrong path in include

---

project.xml

Problem: typo

---

src/zarmour.c
src/zsys.c

Solution: switch statement must handle all values for enumerated
mode. Put conditional code inside case statement.

Problem: zarmour did not build on libzmq 3.x

---

bindings/jni/build.gradle

handwritten fix for #1204 as requested by @hintjens

solution: added ability to publish to local maven repo

---

bindings/ruby/lib/czmq/ffi.rb
bindings/ruby/lib/czmq/ffi/zframe.rb
bindings/ruby/lib/czmq/ffi/zmsg.rb
bindings/ruby/lib/czmq/ffi/zsock.rb

Solution: Regenerate Ruby binding

Problem: Ruby binding lacks behind zproject

---

bindings/jni/src/main/java/org/zeromq/czmq/Zactor.java
bindings/jni/src/main/java/org/zeromq/czmq/Zarmour.java
bindings/jni/src/main/java/org/zeromq/czmq/Zconfig.java
bindings/jni/src/main/java/org/zeromq/czmq/Zdir.java
bindings/jni/src/main/java/org/zeromq/czmq/ZdirPatch.java
bindings/jni/src/main/java/org/zeromq/czmq/Zfile.java
bindings/jni/src/main/java/org/zeromq/czmq/Zhash.java
bindings/jni/src/main/java/org/zeromq/czmq/Zhashx.java
bindings/jni/src/main/java/org/zeromq/czmq/Ziflist.java
bindings/jni/src/main/java/org/zeromq/czmq/Zlist.java
bindings/jni/src/main/java/org/zeromq/czmq/Zloop.java
bindings/jni/src/main/java/org/zeromq/czmq/Zmsg.java
bindings/jni/src/main/java/org/zeromq/czmq/Zpoller.java
bindings/jni/src/main/java/org/zeromq/czmq/Zsock.java
bindings/jni/src/main/java/org/zeromq/czmq/Ztrie.java
bindings/jni/src/main/java/org/zeromq/czmq/Zuuid.java

Solution: fixed in zproject, regenerate here

Problem: JNI API has extraneous 'self' argument

---

issues/issue-407.c
src/zsys.c

A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.
* [Linux kernel coding style](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892)
* [Living in the #ifdef Hell](https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/)
It might improve code understanding, maintainability and error-proneness.

Refactoring conditional directives for incomplete if conditions.

---

bindings/ruby/lib/czmq/ffi.rb
bindings/ruby/lib/czmq/ffi/zactor.rb
bindings/ruby/lib/czmq/ffi/zarmour.rb
bindings/ruby/lib/czmq/ffi/zconfig.rb
bindings/ruby/lib/czmq/ffi/zdir.rb
bindings/ruby/lib/czmq/ffi/zdir_patch.rb
bindings/ruby/lib/czmq/ffi/zfile.rb
bindings/ruby/lib/czmq/ffi/zframe.rb
bindings/ruby/lib/czmq/ffi/zhash.rb
bindings/ruby/lib/czmq/ffi/zhashx.rb
bindings/ruby/lib/czmq/ffi/ziflist.rb
bindings/ruby/lib/czmq/ffi/zlist.rb
bindings/ruby/lib/czmq/ffi/zloop.rb
bindings/ruby/lib/czmq/ffi/zmsg.rb
bindings/ruby/lib/czmq/ffi/zpoller.rb
bindings/ruby/lib/czmq/ffi/zsock.rb
bindings/ruby/lib/czmq/ffi/zstr.rb
bindings/ruby/lib/czmq/ffi/ztrie.rb
bindings/ruby/lib/czmq/ffi/zuuid.rb

Solution: regenerate Ruby binding

Problem: poor Ruby binding documentation

---

bindings/jni/src/main/c/org_zeromq_czmq_Zarmour.c
bindings/jni/src/main/c/org_zeromq_czmq_Zconfig.c
bindings/jni/src/main/c/org_zeromq_czmq_Zdir.c
bindings/jni/src/main/c/org_zeromq_czmq_ZdirPatch.c
bindings/jni/src/main/c/org_zeromq_czmq_Zfile.c
bindings/jni/src/main/c/org_zeromq_czmq_Zframe.c
bindings/jni/src/main/c/org_zeromq_czmq_Zhash.c
bindings/jni/src/main/c/org_zeromq_czmq_Ziflist.c
bindings/jni/src/main/c/org_zeromq_czmq_Zmsg.c
bindings/jni/src/main/c/org_zeromq_czmq_Zsock.c
bindings/jni/src/main/c/org_zeromq_czmq_Zstr.c
bindings/jni/src/main/c/org_zeromq_czmq_Ztrie.c
bindings/jni/src/main/c/org_zeromq_czmq_Zuuid.c
bindings/jni/src/main/java/org/zeromq/czmq/Zframe.java
bindings/jni/src/main/java/org/zeromq/czmq/Zmsg.java
bindings/jni/src/main/java/org/zeromq/czmq/Zuuid.java

Solution: regenerate from zproject
Fixes #1217

Problem: bindings are out of date

---

api/zmsg.xml

Solution: remove singleton flag and first parameter (implicit for non
singleton methods).

Problem: zmsg_load marked as singleton in api model

---

bindings/ruby/lib/czmq/ffi.rb
bindings/ruby/lib/czmq/ffi/zconfig.rb
bindings/ruby/lib/czmq/ffi/zframe.rb
bindings/ruby/lib/czmq/ffi/zhash.rb
bindings/ruby/lib/czmq/ffi/zhashx.rb
bindings/ruby/lib/czmq/ffi/zmsg.rb
bindings/ruby/lib/czmq/ffi/zsock.rb
bindings/ruby/lib/czmq/ffi/zuuid.rb

Problem: Ruby binding outdated

---

include/zarmour.h
include/zframe.h
include/zhash.h
include/zhashx.h
include/ziflist.h
include/zlist.h
include/zloop.h
include/zmsg.h
include/zuuid.h

Problem: missing void in C interfaces

---

api/zcert.xml
api/zcertstore.xml

Problem: copyright notice missing

---

include/czmq_prelude.h
include/zsys.h
src/zbeacon.c
src/zbeacon_v2.c
src/zsys.c

Adding support for IPv6 (zsys, zbeacon, zbeacon_v2 are modified).

Adding support for IPv6 (czmq issue #1236)

---

bindings/ruby/lib/czmq/ffi/zactor.rb
bindings/ruby/lib/czmq/ffi/zarmour.rb
bindings/ruby/lib/czmq/ffi/zcert.rb
bindings/ruby/lib/czmq/ffi/zcertstore.rb
bindings/ruby/lib/czmq/ffi/zconfig.rb
bindings/ruby/lib/czmq/ffi/zdir.rb
bindings/ruby/lib/czmq/ffi/zdir_patch.rb
bindings/ruby/lib/czmq/ffi/zfile.rb
bindings/ruby/lib/czmq/ffi/zframe.rb
bindings/ruby/lib/czmq/ffi/zhash.rb
bindings/ruby/lib/czmq/ffi/zhashx.rb
bindings/ruby/lib/czmq/ffi/ziflist.rb
bindings/ruby/lib/czmq/ffi/zlist.rb
bindings/ruby/lib/czmq/ffi/zloop.rb
bindings/ruby/lib/czmq/ffi/zmsg.rb
bindings/ruby/lib/czmq/ffi/zpoller.rb
bindings/ruby/lib/czmq/ffi/zsock.rb
bindings/ruby/lib/czmq/ffi/zstr.rb
bindings/ruby/lib/czmq/ffi/ztrie.rb
bindings/ruby/lib/czmq/ffi/zuuid.rb

Problem: Ruby binding is outdated wrt zproject

---

include/czmq_prelude.h
src/zbeacon_v2.c

Solution: rename conflicting define to `in4addr`

---

src/zcert.c
src/zdir.c
src/zhashx.c
src/zproxy.c

 Solution: add a space after `assert` where necessary

---

bindings/ruby/lib/czmq/ffi.rb
bindings/ruby/lib/czmq/ffi/zcert.rb

Solution: regenerate Ruby binding

Problem: Ruby binding lacks Zcert#unset_meta

---

src/zactor.c
src/ztrie.c

Problem: duplicate include

---

.travis.yml

Solution: fixed in .travis.yml

Problem: Travis still tries to build qt-android

---

bindings/python/czmq.py
builds/msvc/.gitignore
src/Makemodule.am

See https://travis-ci.org/zeromq/czmq/builds/97634214
Solution: regenerate with latest zproject

Problem: check-py build fails due to syntax error

---

bindings/jni/android/build.sh

Solution: regenerate via zproject

Problem: JNI Android build.sh out of date

---

bindings/jni/android/CMakeLists.txt
bindings/jni/android/build.sh
bindings/jni/msvc/platform.h
builds/android/build.sh
builds/msvc/platform.h
src/zuuid.c

Solution: if __UTYPE_ANDROID, never try to use libuuid.

Problem: uuid link error on Android

---

src/zdir.c
src/zframe.c
src/zlist.c
src/zmsg.c
src/zpoller.c
src/zproxy.c
src/zsock.c
src/ztrie.c

Solution: fix the memory leaks by freeing everything correctly

Problem: valgrind shows a couple of memory leaks

---

project.xml

As discussed in https://github.com/zeromq/zproject/pull/456 and https://github.com/zeromq/zproject/issues/455 these commits set the API status value in the project.xml

Set API status parameter in XML

---

project.xml
src/zuuid.c

Reverts zeromq/czmq#1308
Oops.
I just realized we don't have xml specs for the older classes.

Revert "I don't think class status belongs in project.xml"

---

src/Makemodule.am

Solution: fixed in zproject and rebuilt here.

Problem: czmq_selftest build still not conditional

---

api/zframe.xml
api/zsock.xml
include/zframe.h
include/zsock.h
src/czmq_classes.h
src/zframe.c
src/zsock.c

add radio-dish support to czmq

problem: czmq doesn't support radio-dish

---

ci_build.sh

Solution: regenerate from zproject to use stable branch

Problem: CI build uses unstable libsodium build

---

bindings/ruby/lib/czmq/ffi.rb

Solution: regenerate it with new zproject

Problem: wrong functions names in Ruby binding

---

builds/android/ci_build.sh

Solution: regen from Zproject to pull from stable branch

Problem: Android build uses unstable libsodium

---

api/zsock_option.xml
include/zsockopt.h
src/sockopts.xml
src/zsock_option.inc
src/zsockopt.c

Add pre_allocated_fd sockopt to sockopts.xml and regenerate.

Support of pre-allocated FDs

---

src/Makemodule.am

Solution: fixed in zproject, regenerated here
Fixes #1323

Problem: static links fail due to unresolved libm

---

bindings/jni/src/main/c/org_zeromq_czmq_Zsock.c
bindings/jni/src/main/java/org/zeromq/czmq/Zsock.java
bindings/python/czmq/_czmq_ctypes.py
bindings/python_cffi/czmq_cffi.py
bindings/qml/src/QmlZsock.cpp
bindings/qml/src/QmlZsock.h
bindings/qt/src/qzsock.cpp
bindings/qt/src/qzsock.h
bindings/ruby/lib/czmq/ffi.rb
bindings/ruby/lib/czmq/ffi/zsock.rb
configure.ac
doc/mkman
include/zcert.h
include/zconfig.h
include/zhash.h
include/zhashx.h
include/zmsg.h
include/zproc.h
include/zsock.h
include/zstr.h
src/czmq_classes.h

Problem: out of date with zproject

---

src/zsock.c

Problem: I should read CLASS style more carefully

---

builds/msvc/nuget/package.nuspec
builds/msvc/nuget/package.targets
configure.ac
include/czmq_library.h
project.xml

Needs zproject 1.1.0 or higher
Also regenerated project packaging.

Problem: specify NuGet target options

---

README.txt

Solution: Added Building in Windows section to README.txt

Problem: No Windows build instructions in README.txt

---

README.md

Solution: Updated build instructions in README.md

Problem: Build instructions in README.md out of date

---

README.txt

Solution: Update README.txt with edits done to README.md by newbie contributor (me!).

Problem: README.txt out of date

---

src/zauth.c
src/zauth_v2.c
src/zcert.c
src/zchunk.c

Solution: do nothing, when interrupted
Fixes #1374

Problem: passes null pointer on interrupt (#1374)

---

bindings/ruby/lib/czmq/ffi.rb
bindings/ruby/lib/czmq/ffi/zarmour.rb
bindings/ruby/lib/czmq/ffi/zcert.rb
bindings/ruby/lib/czmq/ffi/zdir_patch.rb
bindings/ruby/lib/czmq/ffi/zframe.rb
bindings/ruby/lib/czmq/ffi/zlist.rb
bindings/ruby/lib/czmq/ffi/zmsg.rb

Problem: Ruby binding outdated wrt zproject

---

bindings/ruby/lib/czmq/ffi/zarmour.rb
bindings/ruby/lib/czmq/ffi/zdir_patch.rb
bindings/ruby/lib/czmq/ffi/zframe.rb

Solution: regenerate with new zproject

Problem: wrong namespace for constants in Ruby binding

---

.gitignore

Solution: git ignore them (and remove duplicate)

Problem: generated script clobber my source tree

---

.gitattributes

Solution: regenerated CZMQ using zproject/tstgenbld.sh
For details, see https://github.com/zeromq/zproject/pull/587

Problem: CZMQ not built using lastest ZPROJECT gsls

---

api/zcert.api
api/zframe.api
api/zmsg.api
api/zpoller.api
api/zsock.api
api/zstr.api
bindings/nodejs/README.md
bindings/nodejs/binding.cc
bindings/nodejs/binding.h
bindings/nodejs/test_binding.js
include/zmsg.h
src/zmsg.c
src/zsock.c
src/zsys.c

The binding can now do Hello, World send/recv via the Zstr class.

Working on Node.js binding

---

api/zsock.api
bindings/nodejs/binding.cc
bindings/nodejs/test_binding.js

Solution: use map values to accept strings as well

Problem: nodejs zsock constructor takes magic numbers

---

bindings/nodejs/README.md
bindings/nodejs/binding.cc
bindings/nodejs/binding.h

Solution: fixed in zproject, was skipping all void methods.

Problem: [nodejs] socket set option API was missing

---

src/zframe.c

This is a tiny PR, but I can't see another way to get access to frame metadata.

ZFrame metadata getter

---

api/zframe.api
src/zframe.c

Added missing unit test and docs from #1389.

Added docs and unit test for zframe_meta()

---

api/zframe.api
bindings/jni/msvc/vs2010/libczmqjni/libczmqjni.props
bindings/jni/msvc/vs2012/libczmqjni/libczmqjni.props
bindings/jni/msvc/vs2013/libczmqjni/libczmqjni.props
bindings/jni/msvc/vs2015/libczmqjni/libczmqjni.props
bindings/jni/src/main/c/org_zeromq_czmq_Zframe.c
bindings/jni/src/main/c/org_zeromq_czmq_Zmsg.c
bindings/jni/src/main/c/org_zeromq_czmq_Zpoller.c
bindings/jni/src/main/java/org/zeromq/czmq/Zframe.java
bindings/jni/src/main/java/org/zeromq/czmq/Zmsg.java
bindings/nodejs/README.md
bindings/nodejs/binding.cc
bindings/nodejs/binding.h
bindings/python/czmq/_czmq_ctypes.py
bindings/python_cffi/czmq_cffi.py
bindings/qml/src/QmlZframe.cpp
bindings/qml/src/QmlZframe.h
bindings/qml/src/QmlZmsg.cpp
bindings/qml/src/QmlZmsg.h
bindings/qt/src/qzframe.cpp
bindings/qt/src/qzframe.h
bindings/qt/src/qzmsg.cpp
bindings/qt/src/qzmsg.h
bindings/ruby/lib/czmq/ffi.rb
bindings/ruby/lib/czmq/ffi/zframe.rb
bindings/ruby/lib/czmq/ffi/zmsg.rb
builds/gyp/project.gyp
ci_build.sh
include/zframe.h
src/zframe.c

Includes bug fix for API to ensure backwards compatibility with ZMQ.

zframe_meta API update

---

bindings/nodejs/index.js
bindings/nodejs/package.json
bindings/nodejs/test_binding.js

Solution: add an index.js
Note: solution does not work, yet.

Problem: [nodejs] need to export constants

---

src/zauth.c

This addresses an existing TODO comment in zauth.

Add certificate metadata to ZAP handler reply

---

src/zsock.c

Solution: use strtoul[l] instead of atol[l]. The latter(s) parse
signed integers, so the last bit is lost.
Fixes #1402

Problem: zsock_recv casts away u32/u64's last bit

---

README.md

Solution: Change 'uuids' to 'UUIDs'

Problem: UUID not in uppercase

---

src/zuuid.c

Solution: force upper case of zuuid_str in all cases

Problem: zuuid_str case inconsistancy

---

README.md
README.txt

Solution: Label the images for clarity

Problem: CI build status images do not include platform

---

README.md
README.txt

Solution: gitdown needs an indent for highlighted section to ignore them

Problem: Comment in highlighted section is misinterpreted as header

---

doc/czmq.txt

Problem: typo in CZMQ manpage

---

api/zframe.api
include/zframe.h

Solution: remove the added additional definition that is not needed.

Problem: zframe group api already included as draft

---

README.md
README.txt

Solution: provide a link directly in the README of zeromq project's

Problem: finding the zeromq irc is too difficult (or not easy enough)

---

README.md
README.txt
doc/ztimerset.doc
doc/ztimerset.txt

Solution: Generate and add it to README!

Problem: There is no README documentation for ztimerset

---

bindings/jni/README.md
bindings/jni/msvc/configure.bat
builds/msvc/configure.bat

Problem: build/bindings are out of sync (zproject has evolved).

---

src/zfile.c

Solution: check the "eof" condition at the right place

Problem: issue #1434 zfile_eof () doesn't work

---

src/zfile.c

Problem: tests for zfile_eof are missing

---

packaging/redhat/czmq.spec

Problem: wrong License and URL Fields in czmq.spec

---

Makefile.am

Problem: autotools out of sync (zproject has evolved!)

---

ci_build.sh

Problem: out of sync with zproject

---

bindings/jni/android/build.sh
bindings/jni/build.gradle
bindings/jni/ci_build.sh
packaging/debian/czmq.install
packaging/redhat/czmq.spec

Problem: jni and packaging out of sync (zproject has evolved!)

---

builds/msvc/vs2010/build.bat
builds/msvc/vs2012/build.bat
builds/msvc/vs2013/build.bat

all visual studio versions now sharing same libzmq.import.props file located at libzmq\builds\vs2015.

fixed libzmq.import.props file path.

---

bindings/jni/ci_build.sh
ci_deploy.sh

Problem: travis + jni out of sync (zproject has evolved!)

---

bindings/jni/ci_build.sh
ci_deploy.sh

Problem: czmq out of sync (zproject has evolved!)

---

Dockerfile
bindings/jni/README.md
project.xml
setup.py

Solution: Add repository attribute which is required for the docker target

Problem: Dockerfile is not generated by zproject

---

src/zhashx.c

Solution: Use the total size of the list instead of the prime index to
store intermediate values before they're serialized, which will be
smaller in case items are chained under one prime index. Also introduce a
new value index to catch all values.

Problem: [zhashx] packing items will fails if they're chained

---

src/zhashx.c

Problem: [zhashx] code does not conform with style guide

---

CMakeLists.txt
builds/cmake/ci_build.sh

Problem: czmq is out of sync (zproject has evolved!)

---

.github/PULL_REQUEST_TEMPLATE.md

Solution: advise contributors to rebase their branches before
sending a pull request and add instructions in the pull request
template.

Problem: recursive merge commits cannot be fixed

---

.github/PULL_REQUEST_TEMPLATE.md

* Problem: No explanation how to get rid of merge commits

Pull Request Template drop merge commits

---

packaging/redhat/czmq.spec

Problem: redhat packaging out of sync (zproject has evolved!)

---

src/zsys.c

Solution: Add some more errors I encountered so debugging is easier in future.

Problem: Some windows errors are not handled

---

src/zbeacon.c

Solution: close the socket on bind failure and attempt on the next interval
Fixes issue #1501

Problem: zbeacon won't reconnect on ip address change

---

include/czmq.h

Solution: Let's honor the request.

Problem: Pieter made a request.

---

api/zsock_option.api
include/zsock.h
src/sockopts.xml
src/zsock_option.inc

Solution: add options to src/sockopt.xml and regenerate

Problem: not all libzmq 4.2 and 4.1 socket options are exposed

---

README.md
README.txt

Solution: Add links to the bindings in the top level README

Problem: Auto generated bindings are not promoted

---

doc/zhashx.doc
doc/zhashx.txt
doc/zsys.doc
doc/zsys.txt
include/zsys.h
src/zsys.c

Solution: add zsys_max_msgsz and zsys_set_max_msgsz and regenerate docs

Problem: no wrapper for new ZMQ_MAX_MSGSZ ctx option

---

bindings/ruby/lib/czmq/ffi.rb

Problem: ruby bindings outdated wrt zproject

---

ci_deploy.sh

Solution: Print more information in case an error occurs

Problem: bintrayUpload fails without proper error message

---

README.md
README.txt

Solution: add note to skip it and regenerate
Fixes https://github.com/zeromq/czmq/issues/1527

Problem: README says to run ldconfig which is wrong for OSX

---

src/zuuid.c

Solution: expand the define's needed for compilation (verified on OpenIndiana)

Problem: zuuid.c does not compile on solaris/illumos

---

.gitignore
builds/check_zproject/ci_build.sh
ci_build.sh

Solution: Regenerate the files
Follow-up to zeromq/czmq#1568 and https://github.com/zeromq/zproject/pull/732

Problem: Generated project structure was not up to date with zproject

---

AUTHORS
src/zbeacon.c
src/zsock.c
src/zstr.c

Solution: Destroy msg if zmsg_send fails.

Problem: memory leak when message send fails

---

.travis.yml
builds/stable_zmq/ci_build.sh

Problems: old Travis OSX workaround not removed, libsodium rebuilt everytime

---

.travis.yml
builds/check_zproject/ci_build.sh
builds/cmake/ci_build.sh
packaging/debian/control

Problems: not using prebuilt packages for CI, out of date with zproject

---

NEWS

Solution: add most relevant bug fixes since 4.0.1

Problem: bug fixes not mentioned in NEWS file

---

CMakeLists.txt
NEWS
configure.ac
project.xml

Solution: regenerate from zproject, set ABI, finalize changelog

Problem: want to release 4.0.2

---

src/zmsg.c

Solution: decrease the size only if the frame was actually removed
and add a simple test case to cover this
Fixes https://github.com/zeromq/czmq/issues/1026

Problem: zmsg_remove updates size no matter if frame is/isn't a member

---

README.md
src/zgossip.c

Solutions: see commits
Fixes #1459

Problems: zgossip doc is misleading, and some APIs are not tested

---

examples/security/strawhouse.c

"ALLOW" is for whitelisting. "PLAIN" requires a password file. In this example it is meant to be whitelisting.
```
```
git push -f
If you are a …

change PLAIN to ALLOW

---

src/zpoller.c

Solution: When using zlist-based implementation (not ZMQ_HAVE_POLLER),
check for existence first. Set errno = EINVAL and return -1 if it
doesn't exist.

Problem: zpoller_remove() does not always fail when removing non-existent reader

---

src/zgossip_engine.inc
src/zsys.c

Solution: fix snprintf (see commits)

Problem: build fails with GCC 7

---

.travis.yml

Problems: travis.yml out of date, cannot change ulimit in containers

---

doc/czmq.txt

Problem: czmq manpage still mentions retired APIs

---

.travis.yml
builds/docs/ci_build.sh

Solution: Add a new build script that will upload the master
revision of the docs to Wikidot on every Non-PR build.

Problem: Wikidot docs are not automatically updated

---

builds/msvc/vs2010/build.bat
builds/msvc/vs2010/czmq.import.props
builds/msvc/vs2010/libczmq/libczmq.import.xml
builds/msvc/vs2010/libczmq/libczmq.vcxproj
builds/msvc/vs2012/build.bat
builds/msvc/vs2012/czmq.import.props
builds/msvc/vs2012/libczmq/libczmq.import.xml
builds/msvc/vs2012/libczmq/libczmq.vcxproj
builds/msvc/vs2013/build.bat
builds/msvc/vs2013/czmq.import.props
builds/msvc/vs2013/libczmq/libczmq.import.xml
builds/msvc/vs2013/libczmq/libczmq.vcxproj
builds/msvc/vs2015/czmq.import.props
builds/msvc/vs2015/libczmq/libczmq.import.xml
builds/msvc/vs2015/libczmq/libczmq.vcxproj
packaging/redhat/czmq.spec
src/Makemodule.am

Solution: regenerate with latest zproject first

Problem: about to add new draft of a class

---

src/zloop.c

Solution: Rebuild pollset after timers if poll needs to be rebuilt.
```
```
git push -f
If you are a new contributor please have a look at our …

Problem: zloop is using reader callback after zloop_reader_end #1634

---

.travis.yml
src/.valgrind.supp
src/zsp.c
src/zsubproc.c

Solution: destroy the poller and add a suppression for glibc thread pool. Plus document the test and code better.

Problem: valgrind build fails

---

src/zsys.c

* pull request #1649 did not contain test
solution :
* add shutdown /init sequence in zsys test

problem : pull request #1649 did not contain test

---

appveyor.yml

Problem: Appveyor build is broken and still uses libsodium

---

src/zbeacon.c
src/ziflist.c
src/zsys.c

Problems: zbeacon still not fully working with IPv6 link-local

---

src/zhashx.c

Solution: fix known consumers and the comments
Addresses issue #1674

Problem: s_zhashx_rehash() no longer returns -1 on errors

---

src/zhashx.c

Solution: make a test to see if it works well

Problem: no selftest for zhashx_purge()

---

api/zargs.api
bindings/lua_ffi/czmq_ffi.lua
bindings/nodejs/README.md
bindings/nodejs/binding.cc
bindings/nodejs/binding.h
bindings/python/czmq/_czmq_ctypes.py
bindings/python_cffi/czmq_cffi/cdefs.py
bindings/ruby/lib/czmq/ffi.rb
include/zargs.h

Solution: name lookup[x] methods right

Problem: python bindings fails

---

src/zconfig.c

Solution: add a test for it
```
```
git push -f …

Problem: don't know how zconfig_str_load works

---

bindings/python_cffi/czmq_cffi/build.py
bindings/python_cffi/czmq_cffi/cdefs.py
bindings/python_cffi/setup.py
packaging/debian/control
packaging/debian/copyright
packaging/debian/czmq.dsc.obs
packaging/debian/rules
packaging/redhat/czmq.spec
src/python_cffi.inc

Problems: no CFFI definition for inaddr_t, out of date with zproject

---

src/zproxy.c

Solution: synchronise using messages instead.
Sync only if a success is expected, to avoid hanging. The second
check with the zpoller still guards against false positives.
The sleeps are very unreliable especially on slow architectures.

Problem: zproxy test sleeps are unreliable and fail

---

packaging/redhat/czmq.spec

Solution: regenerate with latest zproject to get dashes everywhere
```
```
git push -f
If you are a new contributor please have a look at our …

Problem: python2-czmq_cffi name is weird

---

include/czmq_prelude.h
src/zsys.c

Solutions: see commits
Fixes #1700

Problems: buffer overflow on Windows and compile error on XP

---

api/zactor.api
bindings/ruby/lib/czmq/ffi.rb
include/zactor.h
src/czmq_classes.h
src/zactor.c

Problems: new API not marked as draft, memory leak

---

README.md
api/zsock.api
bindings/jni/src/main/java/org/zeromq/czmq/Zframe.java
bindings/jni/src/main/java/org/zeromq/czmq/Zsock.java
bindings/lua_ffi/czmq_ffi.lua
bindings/nodejs/README.md
bindings/python/czmq/_czmq_ctypes.py
bindings/python_cffi/czmq_cffi/_cdefs.inc
bindings/python_cffi/czmq_cffi/cdefs.py
bindings/qml/src/QmlZframe.cpp
bindings/qml/src/QmlZframe.h
bindings/qml/src/QmlZsock.cpp
bindings/qml/src/QmlZsock.h
bindings/qt/src/qzframe.cpp
bindings/qt/src/qzframe.h
bindings/ruby/lib/czmq/ffi/zframe.rb
bindings/ruby/lib/czmq/ffi/zsock.rb
include/zframe.h
include/zsock.h
src/czmq_classes.h
src/zsock.c

Solution: clarify what to do for each supported type and regenerate

Problem: zsock_brecv doc is wrong w.r.t buffer management

---

src/zauth.c
src/zcert.c
src/zcertstore.c
src/zconfig.c
src/zproxy.c

Solution: convert a number of selftests and make them more resilient against possible trash present in the test-dir before their startup.

Problem: More components do not use SELFTEST_DIR

---

src/zhashx.c

Solution: while testing that randof() stays within bounds, also test that it fills these bounds well.

Problem: distribution of randof() is untested

---

src/zdir.c
src/zdir_patch.c

Solution: Enhance zdir.c and zdir_patch.c tests with SELFTEST_DIR_RW support

Problem: A few more components do not use SELFTEST_DIR

---

.travis.yml

Switch to Trusty and avoid installing binutils and ossp-uuid

Problems: Travis using 12.04, and OSX builds are slow

---

appveyor.yml
include/czmq_prelude.h
src/test_randof.c

Solution: add the call to appveyor tests

Problem: test-randof not called in Windows CI

---

README.md
README.txt

Problem: old OBS URLs in README

---

include/zgossip.h
src/zgossip.c
src/zgossip_engine.inc

Problems: zgossip too chatty, binds to hard-coded TCP port, out of date with zproto

---

include/czmq_prelude.h

Solution: Find a relevant #if to include __OpenBSD__

Problem: uint isn't defined on OpenBSD

---

src/zfile.c

Solution: Add a fallback procedure for calculating the file size using ftell fseek
G.md)

Problem: stat is not working with recent VC++ versions on Windows XP

---

src/zfile.c

Solution: hack something using MSDN as a guide
@bluca this is mainly to test the MSDN copy, I don't have any Windows there, so can't really test it. This way it will be built by AppVeyor.

Problem: zfile_tmp does not work on Windows

---

api/zconfig.api
include/zconfig.h
src/czmq_classes.h
src/zconfig.c

SOLUTION: Implement it; Write a test.

PROBLEM: Can't remove zconfig subtree

---

.travis.yml

Solution: add workaround until Travis really fixes the issue:
travis-ci/travis-ci#8552

Problem: Travis builds with brew fail

---

api/zsock_option.api
api/zsys.api
include/zsys.h
src/czmq_classes.h
src/zsock_option.gsl

Revert wrong API changes

---

src/zsys.c

Problems: minor issues with zsys implementation of ctx options wrappers

---

bindings/ruby/lib/czmq/ffi.rb

Problem: Ruby bindings outdated with regards to zproject

---

src/zmonitor.c

Solutions: add em and fix em
Fixes #1805

Problems: no support for new monitor events, fragile ifdefs

---

Jenkinsfile
bindings/python_cffi/czmq_cffi/utils.py
ci_build.sh
configure.ac
doc/Makefile.am
include/czmq_library.h
packaging/redhat/czmq.spec
src/Makemodule.am

Solution: Introduce Jenkinsfile; regenerate with recent zproject

Problem: new goodies available in zproject

---

CMakeLists.txt
bindings/jni/README.md
bindings/jni/android/build.sh
bindings/jni/build.gradle
bindings/jni/msvc/resource.rc
bindings/jni/src/main/java/org/zeromq/czmq/Zconfig.java
bindings/python_cffi/setup.py
bindings/qt/buildlib/buildlib.pro
bindings/ruby/lib/czmq/ffi/version.rb
builds/msvc/nuget/package.nuspec
builds/msvc/nuget/package.targets
builds/msvc/resource.rc
ci_deploy.sh
configure.ac
include/czmq_library.h
packaging/debian/changelog
packaging/debian/czmq.dsc.obs
packaging/redhat/czmq.spec
project.xml

Problems: versions out of date, optional dependencies changed from on by default to off by default

---

src/zfile.c

Solution: add fallback if definition is not available

Problem: build broken on GNU/Hurd due to PATH_MAX

---

src/zfile.c

Fix zfile.c PATH_MAX support consistently with zproc.c and zsys.c precedents

---

include/czmq_prelude.h
src/.valgrind.supp
src/zproc.c

Solution: put macro magic to czmq_prelude.h, so other users will benefit from it. Simplify the zproc.c code a bit.

Problem: zproc readability and usability issues

---

api/zproc.api
include/zproc.h
src/zproc.c

Solution: make better API, fix testing order, improve documentation. See individual commits.

Problem: ergnomy of zproc API is bad

---

include/zproc.h
src/zproc.c

Problem: zproc starting and stopping process is not implmented on win

---

src/zproc.c

but other child processes and parent process too
```int kill( pid_t pid, int sig )```
```If pid is equal to zero, kill() sends the signal sig to all processes whose process group ID is equal to that of the sender, except for those to which the sender does not have the appropriate authority to send a signal```
Solution: if self->pid is still not known -> do nothing
```
```
git remote add upstream …

Problem: zproc_kill may kill not only this process

---

src/zproc.c

Solution: check if std_pipe was properly initialised
```
```
git push -f
If you are a new contributor please have a look at our contributing …

Problem: Valgrind raises "invalid file descriptor -1 in syscall close()"

---

src/zactor.c
src/zchunk.c
src/zframe.c
src/zlistx.c
src/zloop.c
src/zmsg.c
src/zsock.c

```
Problem: zsock_resolve is broken for lots of socket
Solution: 
change ZACTOR_TAG from 0x0005cafe   to 0xcafe0005
change  ZSOCK_TAG   from  0x0004cafe to 0xcafe0004
to make all TAG the same fomat,  change other tag to 0xcafe000x
```

zsock_resolve error for lots of sockets

---

src/zframe.c
src/zsock.c

Solution: set errno to ENOTSUP

Problem: wrong errno set when feature is missing

---

api/zproc.api
include/czmq_library.h
include/zproc.h
src/czmq_classes.h
src/czmq_private_selftest.c
src/czmq_selftest.c
src/zproc.c

PROBLEM: Need getter for zproc cmd line arguments

---

api/python_cffi.slurp
api/zactor.api
bindings/jni/src/main/java/org/zeromq/czmq/Zconfig.java
bindings/lua_ffi/czmq_ffi.lua
bindings/python_cffi/czmq_cffi/cdefs.py
bindings/ruby/lib/czmq/ffi/zactor.rb
include/zactor.h
src/czmq_classes.h
src/zactor.c

Solution: see commits
fixes https://github.com/zeromq/czmq/issues/1867

Problem: custom destructor crashes unit test

---

api/python_cffi.slurp
bindings/jni/src/main/c/org_zeromq_czmq_Zsys.c
bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java
bindings/lua_ffi/czmq_ffi.lua
bindings/nodejs/README.md
bindings/nodejs/binding.cc
bindings/nodejs/binding.h
bindings/python/czmq/_czmq_ctypes.py
bindings/python_cffi/czmq_cffi/Zsys.py
bindings/python_cffi/czmq_cffi/cdefs.py
bindings/qml/src/QmlZsys.cpp
bindings/qml/src/QmlZsys.h
bindings/qt/src/qzsys.cpp
bindings/qt/src/qzsys.h
bindings/ruby/lib/czmq/ffi.rb
bindings/ruby/lib/czmq/ffi/zsys.rb
include/zsys.h
src/czmq_classes.h

Problem: bindings out of date with api/zsys.api

---

.clang-format
NEWS
builds/cmake/Modules/ClangFormat.cmake
builds/cmake/ci_build.sh
ci_build.sh
doc/Makefile.am
src/Makemodule.am

Solution: update NEWS and regenerate zproject

Problem: want to do a new release

---

src/zproc.c

Solution: see commits and added test case

Problem: zproc stdin handling is wrong

---

src/zdir.c

Reverts zeromq/czmq#1894
@jimklimov sorry for the inconvenience

Revert "[WIP] zdir.c : zdir_new() : make sure all inputs are valid"

---

src/zproc.c

Problem: zproc test commented out

---

src/zsys.c

Solution: Set O_CLOEXEC on UDP socket descriptors. Fixes #1899

Problem: UDP socket descriptor leak with exec'd processes

---

appveyor.yml

Solutions: further reduce test_randof and cache libzmq builds

Problems: appveyor still slow

---

src/zproc.c

Problem: zproc_new and zproc_destroy are not safe

---

src/zproc.c
src/zsp.c

Problem: running subprocess which aborts is not tested

---

acinclude.m4
src/CMakeLists-local.txt
src/zsys.c

Problems: SOCK_CLOEXEC ifdef breaks some *nix platforms and CZMQ_HAVE_WINDOWS does not exist

---

src/zproc.c

Solution: Wait for zloop reactor to fill the result

Problem: Using alert() is not thread safe

---

src/zproc.c

Solution: use kill on non Windows to check the process existence. Call
waitpid only from meain thread.
cc @thalman

Problem: calling waitpid from more threads leads to subtle timing errors

---

src/zproc.c

Solution: Move it from zproc_wait to private function,
Check only "running" property in zproc_wait

[WIP] Problem: Waitpid can't be called by user

---

src/zproc.c

Solution: see individual commits, this is mostly the polishing of changes from https://github.com/zeromq/czmq/pull/1920
Tested locally and worked fine.

Problem: zproc robustness is low

---

bindings/jni/src/main/java/org/zeromq/czmq/Zconfig.java

Solution: return the workaround back
cc @bluca

Problem: jni broken

---

src/zproc.c

Solution: when we close the pipe set it fd to -1
```
```
git push -f
If you are a new contributor please have a look at our contributing …

Problem: zproc_destroy can try to close already closed pipe

---

src/zproc.c

Solution: there none atm. This commits adds commented out code
reproducing the issue. Debugging this would take some amount of time
In other words, this is for me to avoid recreating the problem again and make it somewhat visible in source code.

Problem: reading from stdout/stderr blocks forewer

---

src/zcertstore.c
src/zgossip.c
src/zgossip_engine.inc

solution: add them in.
reference: https://github.com/zeromq/zyre/issues/574

problem: draft security features missing '//  DRAFT-API: Security' tag

---

src/zgossip.c

solution: add UNPUBLISH command to force zgossip actor to remove a node from it's tuples list
i tried messing around with various "TTL" ways of ping/pongs, expirations of nodes (using zyre over gossip). since ZYRE keeps track of the nodes (ping, pong, exit, etc) the simplest patch for this was to simply enable things like ZYRE to manually remove a node from the gossip list. less breakage, backwards compatible, etc. this is useful so we're able to at-least trigger things out of the mesh, rather than them living forever (eg: when you use gossip over the Internet).
my ZYRE code simple listens for node EXIT events and then sends an UNPUBLISH down the stack (Zyre API patch forthcoming).
ideally (and I think this is where @hintjens left off?) fiddling with a PING/PONG timer, TTL and some node …

problem: zgossip missing UNPUBLISH command

---

.github/stale.yml

solution: add stale config for stale issues

problem: missing stale config for issues

---

api/zlistx.api
include/zlistx.h
src/czmq_classes.h
src/zsock.c

Solution: Mark new method as draft

Problem: New zlisx_pack/unpack are not marked as draft

---

api/python_cffi.slurp
api/zsock.api
bindings/jni/src/main/java/org/zeromq/czmq/Zconfig.java
bindings/jni/src/main/java/org/zeromq/czmq/Zsock.java
bindings/lua_ffi/czmq_ffi.lua
bindings/nodejs/README.md
bindings/python/czmq/_czmq_ctypes.py
bindings/python_cffi/czmq_cffi/Zsock.py
bindings/python_cffi/czmq_cffi/cdefs.py
bindings/qml/src/QmlZsock.cpp
bindings/qml/src/QmlZsock.h
bindings/qt/src/qzsock.cpp
bindings/qt/src/qzsock.h
bindings/ruby/lib/czmq/ffi/zsock.rb
include/zsock.h
src/zsock.c

Problems: stable builds and JNI fail, DRAFT zsock API not documented

---

configure.ac
project.xml

Solution: require minimum version of libcurl

Problem: using libcurl api which is not available in old versions

---

src/zhttp_client.c

Solution: make it an alias to zactor

Problem: zhttp_client cannot be added to zpoller

---

api/python_cffi.slurp
api/zsys.api
bindings/jni/src/main/c/org_zeromq_czmq_Zsys.c
bindings/jni/src/main/java/org/zeromq/czmq/Zsys.java
bindings/lua_ffi/czmq_ffi.lua
bindings/nodejs/README.md
bindings/nodejs/binding.cc
bindings/nodejs/binding.h
bindings/python/czmq/_czmq_ctypes.py
bindings/python_cffi/czmq_cffi/Zsys.py
bindings/python_cffi/czmq_cffi/cdefs.py
bindings/qml/src/QmlZsys.cpp
bindings/qml/src/QmlZsys.h
bindings/qt/src/qczmq.h
bindings/qt/src/qzsys.cpp
bindings/qt/src/qzsys.h
bindings/ruby/lib/czmq/ffi.rb
bindings/ruby/lib/czmq/ffi/zsys.rb
ci_build.sh
include/zsys.h
src/zsys.c

Problem: new libzmq 4.3.0 context options not supported

---

api/zsock_option.api
src/sockopts.xml
src/zsock_option.inc

Problem: libzmq 4.3 DRAFT socket options not implemented

---

api/python_cffi.slurp
bindings/jni/src/main/c/org_zeromq_czmq_Zsock.c
bindings/jni/src/main/java/org/zeromq/czmq/Zsock.java
bindings/lua_ffi/czmq_ffi.lua
bindings/nodejs/README.md
bindings/nodejs/binding.cc
bindings/nodejs/binding.h
bindings/python/czmq/_czmq_ctypes.py
bindings/python_cffi/czmq_cffi/Zsock.py
bindings/python_cffi/czmq_cffi/cdefs.py
bindings/qml/src/QmlZsock.cpp
bindings/qml/src/QmlZsock.h
bindings/qt/src/qzsock.cpp
bindings/qt/src/qzsock.h
bindings/ruby/lib/czmq/ffi.rb
bindings/ruby/lib/czmq/ffi/zsock.rb
include/czmq_prelude.h
include/zsock.h
src/zuuid.c

Solution: regenerate and move uuid header includes to private file

Problems: socket options not fully regenerated, uuid dependency leaks through public header

---

packaging/redhat/czmq.spec

Solution: regen from zproject to fix it

Problem: syntax error in spec file dependencies

---

api/python_cffi.slurp
api/zchunk.api
api/zframe.api
bindings/delphi/CZMQ.pas
bindings/delphi/libczmq.pas
bindings/jni/src/main/c/org_zeromq_czmq_Zchunk.c
bindings/jni/src/main/java/org/zeromq/czmq/Zchunk.java
bindings/lua_ffi/czmq_ffi.lua
bindings/nodejs/README.md
bindings/nodejs/binding.cc
bindings/nodejs/binding.h
bindings/python/czmq/_czmq_ctypes.py
bindings/python_cffi/czmq_cffi/Zchunk.py
bindings/python_cffi/czmq_cffi/cdefs.py
bindings/qml/src/QmlZchunk.cpp
bindings/qml/src/QmlZchunk.h
bindings/qml/src/QmlZframe.cpp
bindings/qml/src/QmlZframe.h
bindings/qt/src/qzchunk.cpp
bindings/qt/src/qzchunk.h
bindings/qt/src/qzframe.cpp
bindings/qt/src/qzframe.h
bindings/ruby/lib/czmq/ffi.rb
bindings/ruby/lib/czmq/ffi/zchunk.rb
bindings/ruby/lib/czmq/ffi/zframe.rb
include/zchunk.h
include/zframe.h
src/czmq_classes.h
src/zchunk.c
src/zframe.c

Solution: Add constructors that take ownership of the memory

Problem: cannot create zero-copy zframe & zchunk 

---

.travis.yml
builds/abi-compliance-checker/ci_build.sh
ci_deploy_obs.sh

Solutions: regen from zproject

Problem: no ABI checker, OBS release broken 

---

src/zframe.c

Problem: zframe double free

---

NEWS

Solution: add new features and bug fixes since last update

Problem: NEWS out of date with changes

---

src/zproxy.c

Solution: switch to TCP with random available port to avoid
race conditions
Fixes #1998

Problem: zproxy uses fixed ipc endpoint, causing race

---

Findlibzmq.cmake

I have created a PR in `zproject`: https://github.com/zeromq/zproject/pull/1168
Findlibzmq.cmake should be regenerated to fix CMake build error on Win32 (#1972).
TODO;

Problem: Findlibzmq.cmake out of date

---

packaging/redhat/czmq.spec

Solution: regenerate from zproject

Problem: CFFI RPM builds with both python 2 and 3 broken

---

NEWS

Problem: NEWS out of date with recent changes

---

bindings/jni/README.md
builds/android/README.md
builds/android/android_build_helper.sh
builds/android/build.sh
builds/android/ci_build.sh

Solution: Re-generate to upgrade NDK and JNI README

Problem: czmq out of sync with zproject

---

README.md
README.txt

Solution: Add information how to install czmq with package managers on Linux, macOS and Windows

Problem: README no package manager install section

---

ci_deploy.sh

Problem: ci_deploy out of sync with zproject

---

CMakeLists.txt
builds/cmake/Modules/ClangFormat.cmake

Solution: regenerate from zproject

Problem: zproject out of date

---

README.md
README.txt
ci_build.sh
src/czmq_classes.h

Problem: czmq out of sync with latest zproject

---

api/python_cffi.slurp
api/zsock_option.api
bindings/delphi/CZMQ.pas
bindings/delphi/libczmq.pas
bindings/jni/czmq-jni/src/main/c/org_zeromq_czmq_Zsock.c
bindings/jni/czmq-jni/src/main/java/org/zeromq/czmq/Zsock.java
bindings/lua_ffi/czmq_ffi.lua
bindings/nodejs/README.md
bindings/nodejs/binding.cc
bindings/nodejs/binding.h
bindings/python/czmq/_czmq_ctypes.py
bindings/python_cffi/czmq_cffi/Zsock.py
bindings/python_cffi/czmq_cffi/cdefs.py
bindings/qml/src/QmlZsock.cpp
bindings/qml/src/QmlZsock.h
bindings/qt/src/qzsock.cpp
bindings/qt/src/qzsock.h
bindings/ruby/lib/czmq/ffi.rb
bindings/ruby/lib/czmq/ffi/zsock.rb
include/zsock.h
src/sockopts.gsl
src/sockopts.xml
src/zsock_option.gsl
src/zsock_option.inc

problem: no support for disconnect and hello msg socket options

---

src/zconfig.c

https://github.com/zeromq/czmq/issues/2081

FIX #2081 - ZPL: zconfig_chunk_load() fails with 'large' property value

---

src/zsys.c

Solution: Destroy logsender only just before the zmq context is shutdown
@bluca can you still find any race conditions?

Problem: logsender destroyed before last log message

---

src/zbeacon.c

Adding a flag to skip the statement.

Problem: OpenBSD doesn't support `AI_V4MAPPED`

---

src/zgossip.c

Solution: remove useless print message

Problem: useless print message in zgossip

---

src/zgossip.c

Solution: use a zlistx instead because number of monitors will remain very low (as large as the number of gossip servers)

Problem: indexing of monitors does not work with pointers in zhashx

---

api/python_cffi.slurp
bindings/delphi/CZMQ.pas
bindings/delphi/libczmq.pas
bindings/jni/czmq-jni/src/main/c/org_zeromq_czmq_Zcertstore.c
bindings/jni/czmq-jni/src/main/java/org/zeromq/czmq/Zcertstore.java
bindings/lua_ffi/czmq_ffi.lua
bindings/python/czmq/_czmq_ctypes.py
bindings/python_cffi/czmq_cffi/Zcertstore.py
bindings/python_cffi/czmq_cffi/cdefs.py
bindings/qml/src/QmlZcertstore.cpp
bindings/qml/src/QmlZcertstore.h
bindings/qt/src/qzcertstore.cpp
bindings/qt/src/qzcertstore.h
bindings/ruby/lib/czmq/ffi.rb
bindings/ruby/lib/czmq/ffi/zcertstore.rb

Fix: regenerate zproject
Ref. https://github.com/zeromq/zproject/issues/1266

Problem: not aligned with zproject

---

src/zosc.c

Problem: zosc_dup isn't being tested
Solution: implement a test.

zosc_dup wasn't tested

---

builds/stable_zmq/ci_build.sh
ci_build.sh
src/zgossip.c
src/zmonitor.c

Problem: various CI failures

---

api/python_cffi.slurp
api/zosc.api
bindings/jni/czmq-jni/src/main/c/org_zeromq_czmq_Zosc.c
bindings/jni/czmq-jni/src/main/java/org/zeromq/czmq/Zosc.java
bindings/lua_ffi/czmq_ffi.lua
bindings/nodejs/README.md
bindings/nodejs/binding.cc
bindings/nodejs/binding.h
bindings/python/czmq/_czmq_ctypes.py
bindings/python_cffi/czmq_cffi/Zosc.py
bindings/python_cffi/czmq_cffi/cdefs.py
bindings/qml/src/QmlZosc.cpp
bindings/qml/src/QmlZosc.h
bindings/ruby/lib/czmq/ffi.rb
bindings/ruby/lib/czmq/ffi/zosc.rb
ci_build.sh
include/zosc.h
src/zosc.c

Problem: It's not possible to add data to an existing message
Solution: implement an append method

Add zosc_append method

---

src/zhashx.c

Problem: [zhashx] test code did not conform to style guide

---

NEWS

Problem: NEWS out of date with latest changes

---

README.md
api/python_cffi.slurp
api/zsys.api
bindings/delphi/CZMQ.pas
bindings/delphi/libczmq.pas
bindings/jni/czmq-jni/src/main/java/org/zeromq/czmq/Zsys.java
bindings/lua_ffi/czmq_ffi.lua
bindings/nodejs/README.md
bindings/python/czmq/_czmq_ctypes.py
bindings/python_cffi/czmq_cffi/Zsys.py
bindings/python_cffi/czmq_cffi/cdefs.py
bindings/qml/src/QmlZsys.cpp
bindings/qml/src/QmlZsys.h
bindings/ruby/lib/czmq/ffi/zsys.rb
include/zargs.h
include/zsys.h
src/czmq_classes.h
src/zargs.c
src/zproc.c

Problem: typos in manpages

---

src/zsock.c

Problem: There's no STREAM socket test
Solution: add a test similar to libzmq's

Added stream socket test

---

src/zfile.c

Problem: when no path is given to a zfile zfile_output will create a dir with the filename instead of a file 
Solution: don't create a dir if there are no directory delimiters the fullname

don't create the containing dir if there are no delimiters

---

bindings/jni/czmq-jni/android/build.sh

Correction already available in ZProject.
See https://github.com/zeromq/zproject/pull/1301 for details.
```
```
git push -f
If you are a new …

Problem: Android - Build failure on Ubuntu 22.04

---

src/zuuid.c

Problem: Obsolete assignment
Solution: Remove obsolete LOC

zuuid: Drop obsolete assignment

---

README.md
README.txt

`git clone git://gihub.com` no more supported:
```
prompt> grep 'git://github.com' README.md
git clone git://github.com/zeromq/libzmq.git
git clone git://github.com/zeromq/czmq.git
git clone git://github.com/zeromq/libzmq.git
git clone git://github.com/zeromq/czmq.git
git clone git://github.com/zeromq/libzmq.git
git clone git://github.com/zeromq/czmq.git
prompt> git clone git://github.com/zeromq/libzmq.git
Cloning into 'libzmq'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.3]: errno=Connection timed out
prompt>
```
Solution: Change all `git://github.com` with `https://github.com`. See also https://github.com/zeromq/libzmq/pull/4427 for reference.
plausible problem. Further each commit …

Problem: Documentation shows invalid links.

---

builds/android/android_build_helper.sh

Problem: Sync with zproject (Android helpers no not validate dependent libraries.).

---

builds/android/ci_build.sh

Problem: Synch with zproject (builds/android/ci_build.sh must download tarball, when required.).

---

bindings/jni/ci_build.sh
builds/android/ci_build.sh

Solution: Regenerate CZMQ with this commit.

Problem: Sync with zproject (CI build script should allow existing dependency folders).

---

bindings/jni/ci_build.sh
builds/android/build.sh
builds/android/ci_build.sh

Solution: Regenerate CZMQ with this commit.

Problem: Sync with zproject (Android build failures when <dependency>_ROOT is specified)

---

bindings/jni/build.gradle

Solution: Remove JCENTER() call, from Android repository search path.
See
- ZPROJECT [issue 1314](https://github.com/zeromq/zproject/pull/1314) for more details.
- ZPROJECT [issue 1315](https://github.com/zeromq/zproject/pull/1315) for more questions.
```
```
git push -f
In case you already merged instead of …

Problem: JCENTER/BINTRAY no more available for Android repositories

---

bindings/delphi/CZMQ.pas
bindings/delphi/libczmq.pas

Solution: Regenerate Delphi bindings.

Problem: Delphi bindings out of sync with ZProject (mostly about comments).

---

bindings/jni/build.gradle
bindings/jni/ci_build.sh
bindings/jni/czmq-jni-native/build.gradle
bindings/jni/czmq-jni/android/build.sh
builds/android/README.md
builds/android/android_build_helper.sh
builds/android/build.sh
builds/android/ci_build.sh

Solution: Regenerate Android bindings.
Note:
A long pending PR makes Android default build with NDK 25 (formerly NDK 24).

Problem: Android bindings out of sync with ZProject (some long pending PRs).

---

bindings/jni/build.gradle

Solution: Regenerate CZMQ with this commit.

Problem: Sync with zproject (Restore jcenter/bintray Android repository)

---

bindings/jni/ci_build.sh
bindings/jni/czmq-jni/android/build.sh

Solution: Regenerate CZMQ with this commit.

Problem: Sync with zproject (Android CI build need a way to disable GRADLE automatic tests).

---

README.md

Problem: typo in main documentation.

---

bindings/jni/ci_build.sh
builds/android/build.sh

Solution: Generate CZMQ with ZProject (Android modifications only).

Problem: CZMQ (Android) is out of sync with ZProject.

---

include/czmq_prelude.h
src/zactor.c
src/ziflist.c
src/zuuid.c

Solution: add missing directives in various files

Problem: missing directives for IOS compilation

---

src/zhttp_client.c

Solution: Add support for PUT and PATCH methods.

Problem: zhttp_client does not support PUT or PATCH

---

src/zchunk.c

fix zero size zchunk #2297

---

.gitignore

Solution: Fix it according to what is used in zproject & similar projects

Problem: CZMQ ignore some changes from czmq-jni due to bad ignore rules

---

packaging/debian/control
packaging/debian/czmq.dsc
packaging/obs/_service

Problem: out of date with packaging
